/* installer.c — self-extracting installer for the cognitive-os-agent desktop edition.
 *
 * The payload (cognitive-os-agent.exe, launcher, shortcut script, README) is embedded as a
 * generated C array in `payload.inc`, produced by package.sh and #included
 * below. On run, this program writes the files to the install directory and
 * creates the desktop / start-menu shortcuts.
 *
 * Build (package.sh does this):
 *   zig cc -std=c11 -O1 -I dist -o cognitive-os-agent-setup.exe tools/installer.c
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct {
    const char *name;
    const unsigned char *data;
    unsigned long size;
} emb_file;

/* generated by package.sh */
#include "payload.inc"

/* %CADST% override (used by tests / portable installs), else %LOCALAPPDATA%\cognitive-os-agent. */
static int install_dir(char *buf, size_t cap) {
    const char *ov = getenv("CADST");
    if (ov && *ov) {
        snprintf(buf, cap, "%s", ov);
        return 1; /* portable: skip start-menu/desktop shortcuts */
    }
    const char *la = getenv("LOCALAPPDATA");
    if (la && *la) snprintf(buf, cap, "%s\\cognitive-os-agent", la);
    else snprintf(buf, cap, "cognitive-os-agent");
    return 0;
}

static int write_all(const char *dir) {
    char mk[2048];
    snprintf(mk, sizeof(mk), "if not exist \"%s\" mkdir \"%s\"", dir, dir);
    system(mk);

    for (int i = 0; i < g_nfiles; i++) {
        char path[2048];
        snprintf(path, sizeof(path), "%s\\%s", dir, g_files[i].name);
        FILE *fp = fopen(path, "wb");
        if (!fp) {
            fprintf(stderr, "cannot write %s\n", path);
            return -1;
        }
        fwrite(g_files[i].data, 1, g_files[i].size, fp);
        fclose(fp);
    }
    return 0;
}

int main(void) {
    char dir[1024];
    int portable = install_dir(dir, sizeof(dir));

    if (write_all(dir) != 0) {
        printf("cognitive-os-agent install failed\n");
        system("pause");
        return 1;
    }

    if (!portable) {
        /* create desktop + start-menu shortcuts via PowerShell */
        char cmd[2048];
        snprintf(cmd, sizeof(cmd),
                 "powershell -NoProfile -ExecutionPolicy Bypass -File "
                 "\"%s\\make_shortcuts.ps1\" \"%s\"",
                 dir, dir);
        system(cmd);
    }

    printf("\nc-agent installed to %s\n", dir);
    printf("Launch it from the desktop or start-menu shortcut.\n\n");
    system("pause");
    return 0;
}
