/* bench_gaia.c — GAIA-style mini benchmark (Levels 1 & 2 patterns).
 *
 * GAIA evaluates: multi-step tool use, cross-file reasoning, document parsing,
 * (Level 3 adds long-horizon web/GUI work — out of scope, see report). Tasks
 * here mirror GAIA task *shapes* reachable with cognitive-os-agent's tools:
 *   L1: single-file / single-fact extraction and arithmetic
 *   L2: multi-file joins, filtering, aggregation
 * plus one LLM-layer vision task (image understanding, requires a multimodal
 * model — run with --vision; skipped otherwise since deepseek-chat is
 * text-only).
 *
 * Scoring: GAIA official normalization — lowercase, strip punctuation, drop
 * articles (a/an/the), collapse whitespace — then exact match against the
 * expected answer (whole response or its final line). Numeric fallback: if
 * both sides parse as float and are equal, count as correct ("42.50"=="42.5").
 *
 * Fixtures: csv/txt written by this binary; docx/png generated by
 * tools/gen_gaia_fixtures.py (skipped → task SKIP, not FAIL).
 *
 * Modes: --real (default, COA_LLM_* env) / --mock / --vision (adds image task).
 */
#include "cognitive-os-agent/cognitive-os-agent.h"
#include "cognitive-os-agent/llm/llm.h"
#include "cognitive-os-agent/api/websocket.h"
#include "cognitive-os-agent/os/os_fs.h"
#include "cognitive-os-agent/os/os_time.h"
#include "cognitive-os-agent/infra/util.h"

#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "cJSON.h"

#define WS_ROOT "state-bench-gaia/ws"
#define FIXDIR  "state-bench-gaia/ws/gaia"

typedef struct {
    int level;
    const char *name;
    const char *prompt;
    const char *expect;
    int need_docx;   /* skip when contact.docx/report.docx could not be generated */
} gaia_task;

static const gaia_task TASKS[] = {
    /* ---- Level 1: single-source fact / arithmetic ---- */
    {1, "calc",        "What is 17 times 23 minus 91? Answer with the number only.", "300", 0},
    {1, "price",       "The file gaia/products.csv lists products and their prices. What is the price of Widget-B? Answer with the number only.", "42.50", 0},
    {1, "date",        "Read the file gaia/meeting_notes.txt. On what date was the product launch moved to? Answer as MM/DD/YYYY only.", "03/15/2026", 0},
    {1, "docx_email",  "The document gaia/contact.docx contains support information. What is the support contact email address? Answer with the email address only.", "support@example.com", 1},
    {1, "dist",        "A freight truck drives for 3 hours at 80 km/h and then for 2 hours at 95 km/h. What is the total distance traveled in km? Answer with the number only.", "430", 0},
    {1, "attendees",   "Read the file gaia/meeting_notes.txt. How many attendees are listed? Answer with the number only.", "3", 0},
    {1, "cents",       "In gaia/products.csv, what is the price of Widget-D expressed in cents? Answer with the number only.", "975", 0},
    {1, "median",      "The file gaia/numbers.txt contains several numbers, one per line. What is their median? Answer with the number only.", "12", 0},
    /* ---- Level 2: multi-file / multi-step reasoning ---- */
    {2, "revenue",     "gaia/orders.csv lists orders with columns order_id, product, qty, status. gaia/products.csv lists unit prices. What is the total revenue of the orders whose status is shipped? Answer with the number only, rounded to two decimals.", "575.85", 0},
    {2, "count",       "The file gaia/inventory.csv has columns item, quantity, status. How many rows have status shipped AND quantity at least 3? Answer with the number only.", "7", 0},
    {2, "maxrev",      "Using gaia/orders.csv and gaia/products.csv, which product generated the most revenue across the shipped orders? Answer with the product name only.", "Widget-B", 0},
    {2, "latest",      "Read the file gaia/events.txt. Which event happened most recently? Answer with the event name only.", "retrospective", 0},
    {2, "docx_avg",    "The document gaia/report.docx lists three quarterly revenue figures. What is their average? Answer with the number only, rounded to two decimals.", "148.33", 1},
    {2, "sales_pct",   "Read the file gaia/sales.txt. Unit sales grew from January to February. By what percent did they increase? Answer with the number only.", "25", 0},
    {2, "second_price","In gaia/products.csv, which product has the second highest price? Answer with the product name only.", "Widget-B", 0},
    {2, "avg_shipped", "Using gaia/orders.csv and gaia/products.csv, what is the average unit price of the products that appear in at least one shipped order? Answer with the number only, rounded to two decimals.", "31.89", 0},
    {2, "days_between","Read the file gaia/events.txt. How many days elapsed between the kickoff event and the retrospective event? Answer with the number only.", "99", 0},
};
#define N_TASKS ((int)(sizeof(TASKS) / sizeof(TASKS[0])))

/* ---- GAIA-style answer normalization ---- */
static int is_sep(int c) { return !isalnum(c); }

static void normalize(const char *in, char *out, size_t cap) {
    char step[2048];
    size_t o = 0;
    for (const char *p = in; *p && o + 1 < sizeof(step); p++) {
        unsigned char c = (unsigned char)*p;
        if (c >= 'A' && c <= 'Z') c += 32;
        step[o++] = is_sep(c) ? ' ' : (char)c;
    }
    step[o] = '\0';
    /* drop articles, collapse spaces */
    o = 0;
    char prev_space = 1;
    for (size_t i = 0; step[i] && o + 1 < cap; ) {
        if (step[i] == ' ') { if (!prev_space) out[o++] = ' '; prev_space = 1; i++; continue; }
        static const char *const arts[] = {"a ", "an ", "the "};
        int hit = 0;
        if (prev_space) {
            for (size_t a = 0; a < 3; a++) {
                size_t al = strlen(arts[a]);
                if (strncmp(&step[i], arts[a], al) == 0) { i += al; hit = 1; break; }
            }
        }
        if (hit) continue;
        out[o++] = step[i];
        prev_space = 0;
        i++;
    }
    while (o > 0 && out[o - 1] == ' ') o--;
    out[o] = '\0';
}

static int numeric_eq(const char *a, const char *b) {
    char *end = NULL;
    double x = strtod(a, &end);
    if (!end || *end != '\0' || end == a) return 0;
    double y = strtod(b, &end);
    if (!end || *end != '\0' || end == b) return 0;
    return x == y;
}

static int gaia_match(const char *answer, const char *expect) {
    if (!answer || !*answer || !expect) return 0;
    char na[2048], ne[512];
    normalize(answer, na, sizeof(na));
    normalize(expect, ne, sizeof(ne));
    if (!*ne) return 0;
    if (strcmp(na, ne) == 0) return 1;
    /* final non-empty line (harnesses commonly extract the last line) */
    const char *last = answer + strlen(answer);
    while (last > answer) {
        const char *nl = NULL;
        for (const char *q = answer; q < last; q++) if (*q == '\n') nl = q;
        const char *ls = nl ? nl + 1 : answer;
        const char *le = last;
        while (le > ls && isspace((unsigned char)le[-1])) le--;
        while (ls < le && isspace((unsigned char)*ls)) ls++;
        if (le > ls) {
            char line[1024];
            size_t n = (size_t)(le - ls);
            if (n >= sizeof(line)) n = sizeof(line) - 1;
            memcpy(line, ls, n);
            line[n] = '\0';
            char nl2[1024];
            normalize(line, nl2, sizeof(nl2));
            if (strcmp(nl2, ne) == 0) return 1;
            break; /* only the actual last line counts */
        }
        if (nl) last = nl; else break;
    }
    if (numeric_eq(na, ne)) return 1;
    return 0;
}

static void write_fixture(const char *rel, const char *content) {
    char full[1024];
    coa_path_resolve(full, sizeof(full), FIXDIR, rel);
    coa_fs_write_file(full, content, strlen(content));
}

static void make_text_fixtures(void) {
    coa_fs_mkdirs(FIXDIR);
    write_fixture("products.csv",
        "product,price\nWidget-A,17.30\nWidget-B,42.50\nWidget-C,58.00\nWidget-D,9.75\n");
    write_fixture("orders.csv",
        "order_id,product,qty,status\n"
        "1001,Widget-A,2,shipped\n1002,Widget-B,1,pending\n1003,Widget-C,3,shipped\n"
        "1004,Widget-A,1,shipped\n1005,Widget-D,5,shipped\n1006,Widget-B,2,shipped\n"
        "1007,Widget-C,1,pending\n1008,Widget-D,2,shipped\n1009,Widget-A,4,shipped\n"
        "1010,Widget-B,3,shipped\n");
    write_fixture("inventory.csv",
        "item,quantity,status\n"
        "bolt,10,shipped\nnut,2,pending\ngear,3,shipped\nbolt,1,shipped\n"
        "nut,5,shipped\ngear,4,pending\nbolt,7,pending\nnut,3,shipped\n"
        "gear,12,shipped\nbolt,2,pending\nnut,1,shipped\ngear,6,shipped\n"
        "bolt,9,pending\nnut,4,pending\ngear,2,shipped\nbolt,3,shipped\n"
        "nut,8,pending\ngear,1,pending\nbolt,5,pending\nnut,6,pending\n");
    write_fixture("events.txt",
        "2026-01-05 kickoff\n2026-02-11 design review\n2026-03-27 beta release\n"
        "2026-04-14 retrospective\n");
    write_fixture("meeting_notes.txt",
        "Product sync - 2026-02-20\n"
        "Attendees: Lin, Mara, Joel\n"
        "Engineering reports the billing integration is on track.\n"
        "Marketing asked for more lead time, so the product launch date is "
        "moved to March 15, 2026.\n"
        "Next sync scheduled for the following Tuesday.\n");
    write_fixture("numbers.txt", "12\n7\n45\n9\n33\n");
    write_fixture("sales.txt", "Month,units\nJan,240\nFeb,300\n");
}

static int run_python_fixtures(void) {
    if (system("python3 tools/gen_gaia_fixtures.py " FIXDIR " > gaia_fixtures.log 2>&1") != 0 &&
        system("python tools/gen_gaia_fixtures.py " FIXDIR " >> gaia_fixtures.log 2>&1") != 0)
        return 0;
    char full[1024];
    coa_path_resolve(full, sizeof(full), FIXDIR, "contact.docx");
    if (coa_fs_read_file(full)) return 1;
    return 0;
}

/* ---- vision task (LLM layer; needs a multimodal model) ---- */
static int vision_task(coa_llm *llm, char **answer_out) {
    char full[1024];
    coa_path_resolve(full, sizeof(full), FIXDIR, "diagram.png");
    FILE *f = fopen(full, "rb");
    if (!f) return -1;
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (len <= 0) { fclose(f); return -1; }
    unsigned char *png = (unsigned char *)malloc((size_t)len);
    if (!png || fread(png, 1, (size_t)len, f) != (size_t)len) {
        free(png);
        fclose(f);
        return -1;
    }
    fclose(f);
    char *b64 = coa_base64_encode(png, (size_t)len);
    free(png);
    if (!b64) return -1;
    coa_llm_message msgs[1] = {
        {"user", "What is the 4-digit access code shown in the image? Answer with the digits only.", b64, "image/png"},
    };
    coa_llm_request req;
    memset(&req, 0, sizeof(req));
    req.messages = msgs;
    req.num_messages = 1;
    req.temperature = 0.2;
    /* reasoning models burn token budget on thinking before answering; 256
     * starves them into an empty content (seen with GLM-5.3-flash) */
    req.max_tokens = 4096;
    coa_llm_response resp;
    memset(&resp, 0, sizeof(resp));
    int rc = coa_llm_chat(llm, &req, &resp);
    free(b64);
    if (rc != 0) { free(resp.error); return -1; }
    *answer_out = resp.content;
    return 0;
}

int main(int argc, char **argv) {
    int real = 1, vision = 0;
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--real") == 0) real = 1;
        else if (strcmp(argv[i], "--mock") == 0) real = 0;
        else if (strcmp(argv[i], "--vision") == 0) vision = 1;
        else { fprintf(stderr, "usage: %s [--mock|--real] [--vision]\n", argv[0]); return 2; }
    }

    coa_config cfg;
    memset(&cfg, 0, sizeof(cfg));
    cfg.state_root = "state-bench-gaia";
    cfg.workspace  = WS_ROOT;
    cfg.http_port  = 0;
    if (real) {
        cfg.provider = getenv("COA_LLM_PROVIDER");
        cfg.base_url = getenv("COA_LLM_BASE_URL");
        cfg.api_key  = getenv("COA_LLM_API_KEY");
        cfg.model    = getenv("COA_LLM_MODEL");
        if (!cfg.provider || !*cfg.provider) cfg.provider = "openai";
    } else {
        cfg.provider = "mock";
    }

    coa_ctx ctx;
    if (coa_init(&ctx, &cfg) != 0) {
        fprintf(stderr, "bench_gaia: coa_init failed (provider=%s)\n",
                cfg.provider ? cfg.provider : "?");
        return 1;
    }
    printf("cognitive-os-agent GAIA-style benchmark [%s] provider=%s model=%s\n\n",
           real ? "REAL" : "MOCK", ctx.provider ? ctx.provider : "?",
           getenv("COA_LLM_MODEL") ? getenv("COA_LLM_MODEL") : "?");

    coa_fs_mkdirs(WS_ROOT);
    make_text_fixtures();
    int docx_ok = run_python_fixtures();
    printf("fixtures: text=ok docx=%s\n\n", docx_ok ? "ok" : "SKIP");

    int l1_ok = 0, l1_n = 0, l2_ok = 0, l2_n = 0;
    int64_t t0 = coa_time_now_ms();
    for (int i = 0; i < N_TASKS; i++) {
        const gaia_task *t = &TASKS[i];
        if (t->need_docx && !docx_ok) {
            printf("  [L%d/%-10s] SKIP (docx fixture unavailable)\n", t->level, t->name);
            continue;
        }
        char *answer = NULL;
        int64_t s0 = coa_time_now_ms();
        int rc = coa_run(&ctx, t->prompt, &answer);
        int64_t lat = coa_time_now_ms() - s0;
        int ok = (rc == 0) && gaia_match(answer, t->expect);
        if (t->level == 1) { l1_n++; l1_ok += ok; } else { l2_n++; l2_ok += ok; }
        printf("  [L%d/%-10s] %s lat=%lldms answer=\"%.80s\" expect=%s\n",
               t->level, t->name, ok ? "PASS" : "FAIL", (long long)lat,
               answer ? answer : "(null)", t->expect);
        free(answer);
    }

    int vis_ok = -1; /* -1 = skipped */
    if (vision) {
        char *answer = NULL;
        int64_t s0 = coa_time_now_ms();
        int rc = vision_task(ctx.llm, &answer);
        int64_t lat = coa_time_now_ms() - s0;
        if (rc == 0) {
            vis_ok = gaia_match(answer, "7392");
            printf("  [V/vision-code] %s lat=%lldms answer=\"%.80s\" expect=7392\n",
                   vis_ok ? "PASS" : "FAIL", (long long)lat, answer);
        } else {
            printf("  [V/vision-code] FAIL lat=%lldms (image request failed - model may be text-only)\n",
                   (long long)lat);
        }
        free(answer);
    }

    int64_t total = coa_time_now_ms() - t0;
    coa_shutdown(&ctx);

    int tot_n = l1_n + l2_n, tot_ok = l1_ok + l2_ok;
    /* leaderboard-style scores (GAIA official reports percentages) */
    double l1_pct = l1_n ? 100.0 * l1_ok / l1_n : 0.0;
    double l2_pct = l2_n ? 100.0 * l2_ok / l2_n : 0.0;
    double avg_pct = tot_n ? 100.0 * tot_ok / tot_n : 0.0;
    printf("\n== scores (leaderboard format) ==\n");
    printf("  Average score   : %.2f%%  (%d/%d)\n", avg_pct, tot_ok, tot_n);
    printf("  Level 1 score   : %.2f%%  (%d/%d)\n", l1_pct, l1_ok, l1_n);
    printf("  Level 2 score   : %.2f%%  (%d/%d)\n", l2_pct, l2_ok, l2_n);
    if (vision) printf("  vision (L1-style) : %s\n",
                      vis_ok < 0 ? "skipped (--vision set but unavailable)" :
                      vis_ok ? "1/1" : "0/1");
    printf("  total wall time: %lldms\n", (long long)total);

    cJSON *j = cJSON_CreateObject();
    cJSON_AddNumberToObject(j, "avg_score_pct", avg_pct);
    cJSON_AddNumberToObject(j, "l1_score_pct", l1_pct);
    cJSON_AddNumberToObject(j, "l2_score_pct", l2_pct);
    cJSON_AddNumberToObject(j, "l1_ok", l1_ok);
    cJSON_AddNumberToObject(j, "l1_total", l1_n);
    cJSON_AddNumberToObject(j, "l2_ok", l2_ok);
    cJSON_AddNumberToObject(j, "l2_total", l2_n);
    cJSON_AddNumberToObject(j, "total_ok", tot_ok);
    cJSON_AddNumberToObject(j, "total_n", tot_n);
    if (vision) cJSON_AddNumberToObject(j, "vision_ok", vis_ok);
    cJSON_AddNumberToObject(j, "total_ms", (double)total);
    char *js = cJSON_PrintUnformatted(j);
    printf("  JSON: %s\n", js ? js : "{}");
    free(js);
    cJSON_Delete(j);
    return 0;
}
