/* web_ui.h - GENERATED from apps/web/index.html by tools/gen_web_ui.py.
 * Do not edit by hand; re-run the generator after changing the HTML. */
#pragma once
static const char ca_web_index_html[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"zh-CN\">\n"
    "<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "<meta name=\"color-scheme\" content=\"dark light\">\n"
    "<title>c-agent — Cognitive OS Console</title>\n"
    "<style>\n"
    "  /* ---------- design tokens ---------- */\n"
    "  :root{\n"
    "    --radius:10px; --radius-sm:7px; --radius-xs:5px;\n"
    "    --tr-dur:150ms;\n"
    "    --mono:ui-monospace,\"Cascadia Code\",Consolas,\"JetBrains Mono\",monospace;\n"
    "    --sans:system-ui,-apple-system,\"Segoe UI\",Roboto,\"Microsoft YaHei\",\"PingFang SC\",sans-serif;\n"
    "    --side-w:232px;\n"
    "  }\n"
    "  /* base = dark theme */\n"
    "  body{\n"
    "    margin:0; font-family:var(--sans); font-size:13px; line-height:1.5;\n"
    "    color-scheme:dark;\n"
    "    background:#0b0e14; color:#e7ecf3;\n"
    "    --bg:#0b0e14; --card:#141821; --border:#232a37;\n"
    "    --fg:#e7ecf3; --muted:#8b94a7;\n"
    "    --accent:#3b82f6; --ok:#34d399; --warn:#fbbf24; --danger:#f87171;\n"
    "    --sidebar:#080b10; --nav-hover:#11141b; --nav-on:#151b28; --input:#232b3a;\n"
    "    --code-num:#c084fc;\n"
    "    --accent-soft:color-mix(in srgb, var(--accent) 13%, transparent);\n"
    "    --accent-ring:color-mix(in srgb, var(--accent) 42%, transparent);\n"
    "    --card-hover:color-mix(in srgb, var(--fg) 4%, var(--card));\n"
    "    --shadow:0 1px 2px rgba(0,0,0,.28), 0 12px 32px rgba(0,0,0,.24);\n"
    "    --shadow-sm:0 1px 2px rgba(0,0,0,.2);\n"
    "    display:flex; height:100vh; overflow:hidden;\n"
    "  }\n"
    "  body[data-theme=light]{\n"
    "    color-scheme:light;\n"
    "    background:#f3f5f9; color:#1b2233;\n"
    "    --bg:#f3f5f9; --card:#ffffff; --border:#dfe4ee;\n"
    "    --fg:#1b2233; --muted:#5b6478;\n"
    "    --accent:#2563eb; --ok:#059669; --warn:#b45309; --danger:#dc2626;\n"
    "    --sidebar:#e9edf4; --nav-hover:#dfe5ef; --nav-on:#ffffff; --input:#d3dbe8;\n"
    "    --code-num:#7c3aed;\n"
    "    --shadow:0 1px 3px rgba(23,34,58,.08), 0 12px 32px rgba(23,34,58,.12);\n"
    "    --shadow-sm:0 1px 2px rgba(23,34,58,.06);\n"
    "  }\n"
    "  body[data-theme=ocean]{\n"
    "    color-scheme:dark;\n"
    "    background:#081120; color:#d8e9ff;\n"
    "    --bg:#081120; --card:#0d1a2d; --border:#1c3350;\n"
    "    --fg:#d8e9ff; --muted:#7fa3c9;\n"
    "    --accent:#38bdf8; --ok:#34d399; --warn:#fbbf24; --danger:#fb7185;\n"
    "    --sidebar:#060d18; --nav-hover:#0e2138; --nav-on:#113052; --input:#1c3350;\n"
    "    --code-num:#a5b4fc;\n"
    "  }\n"
    "  body[data-theme=forest]{\n"
    "    color-scheme:dark;\n"
    "    background:#0c1310; color:#d9f2e4;\n"
    "    --bg:#0c1310; --card:#132019; --border:#21372c;\n"
    "    --fg:#d9f2e4; --muted:#8fb8a0;\n"
    "    --accent:#34d399; --ok:#4ade80; --warn:#fbbf24; --danger:#f87171;\n"
    "    --sidebar:#0a100c; --nav-hover:#15241c; --nav-on:#1a3a2a; --input:#21372c;\n"
    "    --code-num:#86efac;\n"
    "  }\n"
    "  body[data-theme=sunset]{\n"
    "    color-scheme:dark;\n"
    "    background:#160f1a; color:#f1e3f0;\n"
    "    --bg:#160f1a; --card:#221a26; --border:#392b41;\n"
    "    --fg:#f1e3f0; --muted:#b19ab3;\n"
    "    --accent:#e879f9; --ok:#4ade80; --warn:#fbbf24; --danger:#fb7185;\n"
    "    --sidebar:#110c15; --nav-hover:#291e2e; --nav-on:#392b41; --input:#392b41;\n"
    "    --code-num:#f0abfc;\n"
    "  }\n"
    "\n"
    "  *{box-sizing:border-box}\n"
    "  ::selection{background:var(--accent-ring)}\n"
    "  ::-webkit-scrollbar{width:10px;height:10px}\n"
    "  ::-webkit-scrollbar-thumb{background:var(--border);border-radius:6px;border:2px solid transparent;background-clip:content-box}\n"
    "  ::-webkit-scrollbar-thumb:hover{background:var(--muted);background-clip:content-box}\n"
    "  ::-webkit-scrollbar-track{background:transparent}\n"
    "\n"
    "  aside{\n"
    "    width:var(--side-w); flex-shrink:0; height:100vh;\n"
    "    background:var(--sidebar); border-right:1px solid var(--border);\n"
    "    display:flex; flex-direction:column; z-index:30; transition:transform var(--tr-dur) ease;\n"
    "  }\n"
    "  .brand{display:flex; align-items:center; gap:10px; padding:16px 14px 14px; border-bottom:1px solid var(--border)}\n"
    "  .logo{\n"
    "    width:34px; height:34px; border-radius:9px; flex-shrink:0; display:grid; place-items:center;\n"
    "    background:linear-gradient(135deg, var(--accent), color-mix(in srgb, var(--accent) 62%, #000 0%));\n"
    "    color:#fff; font-size:17px; font-weight:800; letter-spacing:-1px; user-select:none;\n"
    "    box-shadow:inset 0 1px 0 rgba(255,255,255,.18), 0 2px 6px color-mix(in srgb, var(--accent) 35%, transparent);\n"
    "  }\n"
    "  .brand h1{margin:0; font-size:15px; font-weight:700; letter-spacing:.2px}\n"
    "  .brand .sub{color:var(--muted); font-size:11px; margin-top:1px}\n"
    "  nav{flex:1; overflow-y:auto; padding:8px 0}\n"
    "  nav button{\n"
    "    display:flex; align-items:center; gap:10px; width:100%;\n"
    "    background:none; border:0; border-left:3px solid transparent;\n"
    "    color:var(--muted); padding:8px 13px; font-size:13px; cursor:pointer; text-align:left;\n"
    "    transition:color var(--tr-dur), background var(--tr-dur);\n"
    "  }\n"
    "  nav button svg{flex-shrink:0; opacity:.9}\n"
    "  nav button:hover{background:var(--nav-hover); color:var(--fg)}\n"
    "  nav button:focus-visible{outline:2px solid var(--accent-ring); outline-offset:-2px}\n"
    "  nav button.on, nav button[aria-current=\"true\"]{\n"
    "    background:var(--nav-on); border-left-color:var(--accent); color:var(--fg); font-weight:600;\n"
    "  }\n"
    "  .side-foot{padding:12px 14px; border-top:1px solid var(--border)}\n"
    "  .conn{display:flex; align-items:center; gap:8px; font-size:12px; color:var(--muted)}\n"
    "  .dot{width:8px; height:8px; border-radius:50%; display:inline-block; flex-shrink:0}\n"
    "  .dot.ok{background:var(--ok)}\n"
    "  .dot.warn{background:var(--warn)}\n"
    "  .dot.err{background:var(--danger)}\n"
    "  .dot.pulse{animation:blink 1.6s ease-in-out infinite}\n"
    "  @keyframes blink{0%,100%{opacity:1}50%{opacity:.35}}\n"
    "\n"
    "  main{flex:1; display:flex; flex-direction:column; min-width:0; height:100vh}\n"
    "  .top{\n"
    "    display:flex; align-items:center; justify-content:space-between; gap:12px;\n"
    "    padding:11px 18px; border-bottom:1px solid var(--border); background:var(--card); flex-shrink:0;\n"
    "  }\n"
    "  .top-left{display:flex; align-items:center; gap:10px; min-width:0}\n"
    "  .title{font-size:14px; font-weight:650; letter-spacing:.2px; outline:none}\n"
    "  .flow{color:var(--muted); font-size:11px; letter-spacing:.45px; white-space:nowrap; user-select:none}\n"
    "  .topright{display:flex; align-items:center; gap:10px}\n"
    "  .icon-btn{\n"
    "    width:32px; height:32px; display:grid; place-items:center;\n"
    "    background:none; border:1px solid transparent; border-radius:var(--radius-sm);\n"
    "    color:var(--muted); cursor:pointer; padding:0;\n"
    "    transition:color var(--tr-dur), background var(--tr-dur), border-color var(--tr-dur);\n"
    "  }\n"
    "  .icon-btn:hover{color:var(--fg); background:var(--accent-soft); border-color:color-mix(in srgb, var(--accent) 30%, transparent)}\n"
    "  .icon-btn:focus-visible{outline:2px solid var(--accent-ring); outline-offset:2px}\n"
    "  #navToggle{display:none}\n"
    "  .content{flex:1; padding:20px; overflow-y:auto; scrollbar-gutter:stable}\n"
    "\n"
    "  .card{background:var(--card); border:1px solid var(--border); border-radius:var(--radius); padding:16px; margin-bottom:14px; box-shadow:var(--shadow-sm)}\n"
    "  .card h2{margin:0 0 4px; font-size:13px; font-weight:650}\n"
    "  .card-head{display:flex; align-items:center; justify-content:space-between; gap:10px; margin-bottom:8px}\n"
    "  .card-head h2{margin:0}\n"
    "  .card-head .row{margin:0; gap:6px}\n"
    "  .hint{color:var(--muted); font-size:12px; margin:0 0 10px; line-height:1.65}\n"
    "  .muted{color:var(--muted)}\n"
    "\n"
    "  textarea,input[type=text],input[type=number],select{\n"
    "    width:100%; background:var(--bg); color:var(--fg);\n"
    "    border:1px solid var(--border); border-radius:var(--radius-sm);\n"
    "    padding:8px 10px; font-size:12.5px;\n"
    "    transition:border-color var(--tr-dur), box-shadow var(--tr-dur);\n"
    "  }\n"
    "  textarea,input[type=text],input[type=number]{font-family:var(--mono)}\n"
    "  textarea:focus,input[type=text]:focus,input[type=number]:focus,select:focus{\n"
    "    outline:none; border-color:var(--accent); box-shadow:0 0 0 3px var(--accent-ring);\n"
    "  }\n"
    "  textarea{height:76px; resize:vertical; line-height:1.55}\n"
    "  select{height:34px; width:auto; min-width:96px; cursor:pointer; font-family:var(--sans); font-size:12.5px; padding:0 26px 0 10px}\n"
    "  ::placeholder{color:var(--muted); opacity:.75}\n"
    "\n"
    "  button{\n"
    "    background:var(--accent); color:#fff; border:0; border-radius:var(--radius-sm);\n"
    "    padding:8px 14px; font-size:12.5px; font-weight:600; cursor:pointer; font-family:var(--sans);\n"
    "    transition:filter var(--tr-dur), transform var(--tr-dur), background var(--tr-dur), border-color var(--tr-dur), color var(--tr-dur);\n"
    "  }\n"
    "  button:hover{filter:brightness(1.08)}\n"
    "  button:active{transform:translateY(1px)}\n"
    "  button:focus-visible{outline:2px solid var(--accent-ring); outline-offset:2px}\n"
    "  button:disabled{opacity:.5; cursor:not-allowed; filter:none; transform:none}\n"
    "  button.sec{background:var(--card); border:1px solid var(--border); color:var(--fg)}\n"
    "  button.sec:hover{background:var(--card-hover)}\n"
    "  button.danger{background:transparent; color:var(--danger); border:1px solid var(--danger)}\n"
    "  button.danger:hover{background:color-mix(in srgb, var(--danger) 12%, transparent)}\n"
    "  button.sm{padding:4px 9px; font-size:11.5px; font-weight:600}\n"
    "  .row{display:flex; gap:8px; align-items:center; margin-top:10px; flex-wrap:wrap}\n"
    "\n"
    "  pre{\n"
    "    background:var(--bg); border:1px solid var(--border); border-radius:var(--radius-sm);\n"
    "    padding:12px; font-size:12px; line-height:1.55; margin:0;\n"
    "    overflow:auto; white-space:pre-wrap; word-break:break-word;\n"
    "    max-height:55vh; min-height:56px; font-family:var(--mono);\n"
    "  }\n"
    "  .json .k{color:var(--accent); font-weight:600}\n"
    "  .json .s{color:var(--ok)}\n"
    "  .json .b{color:var(--warn)}\n"
    "  .json .num{color:var(--code-num)}\n"
    "  .json .n{color:var(--danger)}\n"
    "  .json .p{color:var(--muted)}\n"
    "  .json .empty{color:var(--muted); font-style:italic}\n"
    "\n"
    "  .table-wrap{overflow:auto; border:1px solid var(--border); border-radius:var(--radius-sm); margin-top:8px}\n"
    "  table{width:100%; border-collapse:collapse; font-size:12.5px}\n"
    "  thead th{position:sticky; top:0; z-index:1; background:var(--card); text-align:left; padding:9px 12px; border-bottom:1px solid var(--border); color:var(--muted); font-weight:600; white-space:nowrap}\n"
    "  td{padding:8px 12px; border-bottom:1px solid var(--border); vertical-align:top}\n"
    "  tbody tr{transition:background var(--tr-dur)}\n"
    "  tbody tr:hover{background:var(--card-hover)}\n"
    "  tr.active-row td{background:var(--accent-soft)}\n"
    "  tr.active-row td:first-child{box-shadow:inset 3px 0 0 var(--accent)}\n"
    "\n"
    "  .badge{display:inline-block; padding:1px 7px; border-radius:999px; font-size:11px; font-weight:600; white-space:nowrap}\n"
    "  .badge-ok{background:color-mix(in srgb, var(--ok) 16%, transparent); color:var(--ok)}\n"
    "  .badge-warn{background:color-mix(in srgb, var(--warn) 16%, transparent); color:var(--warn)}\n"
    "  .badge-err{background:color-mix(in srgb, var(--danger) 16%, transparent); color:var(--danger)}\n"
    "  .chips{display:flex; flex-wrap:wrap; gap:6px}\n"
    "  .chip{\n"
    "    display:inline-flex; align-items:center; gap:6px; max-width:100%;\n"
    "    padding:4px 10px; background:var(--bg); border:1px solid var(--border);\n"
    "    border-radius:999px; font-size:12px; cursor:pointer; color:var(--fg);\n"
    "    transition:border-color var(--tr-dur), color var(--tr-dur);\n"
    "  }\n"
    "  .chip b{color:var(--muted); font-weight:700; flex-shrink:0}\n"
    "  .chip span{overflow:hidden; text-overflow:ellipsis; white-space:nowrap}\n"
    "  .chip:hover{border-color:var(--accent); color:var(--accent)}\n"
    "\n"
    "  .toast{position:fixed; bottom:24px; left:50%; transform:translate(-50%, 12px); background:var(--fg); color:var(--bg); padding:8px 16px; border-radius:8px; font-size:12.5px; font-weight:600; opacity:0; pointer-events:none; z-index:99; box-shadow:var(--shadow); transition:opacity var(--tr-dur), transform var(--tr-dur)}\n"
    "  .toast.show{opacity:1; transform:translate(-50%, 0)}\n"
    "  .backdrop{position:fixed; inset:0; background:rgba(0,0,0,.45); z-index:20; display:none; backdrop-filter:blur(2px)}\n"
    "\n"
    "  /* ---------- dashboard stats ---------- */\n"
    "  .stat-grid{display:grid; grid-template-columns:repeat(auto-fill,minmax(150px,1fr)); gap:12px}\n"
    "  .stat{padding:14px 16px; border:1px solid var(--border); border-radius:var(--radius); background:var(--card)}\n"
    "  .stat .num{font-size:22px; font-weight:700}\n"
    "  .stat .lbl{font-size:11.5px; color:var(--muted); margin-top:2px}\n"
    "\n"
    "  /* ---------- IM ---------- */\n"
    "  .im-layout{display:grid; grid-template-columns:250px 1fr; gap:14px; align-items:start}\n"
    "  .im-sessions{display:flex; flex-direction:column; gap:6px; max-height:calc(100vh - 260px); overflow-y:auto; padding-right:2px}\n"
    "  .im-session{padding:9px 12px; border:1px solid var(--border); border-radius:var(--radius-sm); cursor:pointer; font-size:12.5px; background:var(--bg); transition:all var(--tr-dur); display:flex; justify-content:space-between; align-items:center; gap:6px}\n"
    "  .im-session:hover{border-color:var(--accent)}\n"
    "  .im-session.on{background:var(--accent-soft); border-color:var(--accent)}\n"
    "  .im-session .del{color:var(--muted); background:none; border:0; padding:0 2px; font-size:12px; cursor:pointer}\n"
    "  .im-session .del:hover{color:var(--danger)}\n"
    "  .im-session .name{overflow:hidden; text-overflow:ellipsis; white-space:nowrap}\n"
    "  .im-thread{display:flex; flex-direction:column; gap:8px; max-height:calc(100vh - 340px); min-height:180px; overflow-y:auto; padding:4px}\n"
    "  .im-msg{max-width:80%; padding:9px 12px; border-radius:12px; font-size:13px; line-height:1.55; white-space:pre-wrap; word-break:break-word}\n"
    "  .im-msg.user{align-self:flex-end; background:var(--accent); color:#fff; border-bottom-right-radius:3px}\n"
    "  .im-msg.assistant{align-self:flex-start; background:var(--bg); border:1px solid var(--border); border-bottom-left-radius:3px}\n"
    "  .im-msg .meta{font-size:10.5px; opacity:.75; margin-top:3px}\n"
    "  .im-input-row{display:flex; gap:8px; margin-top:10px}\n"
    "  .im-input-row input{flex:1}\n"
    "  @media (max-width:760px){.im-layout{grid-template-columns:1fr}}\n"
    "\n"
    "  .spin{display:inline-block; width:12px; height:12px; border:2px solid var(--border); border-top-color:var(--accent); border-radius:50%; animation:rot .8s linear infinite; vertical-align:-2px}\n"
    "  @keyframes rot{to{transform:rotate(360deg)}}\n"
    "\n"
    "  @media (max-width:899px){\n"
    "    #navToggle{display:grid}\n"
    "    aside{position:fixed; left:0; top:0; bottom:0; transform:translateX(-100%)}\n"
    "    aside.open{transform:translateX(0); box-shadow:var(--shadow)}\n"
    "    .backdrop.on{display:block}\n"
    "    .flow{display:none}\n"
    "  }\n"
    "  @media (max-width:600px){\n"
    "    .content{padding:14px}\n"
    "    .card{padding:14px}\n"
    "    .top{padding:10px 12px}\n"
    "  }\n"
    "  @media (prefers-reduced-motion:reduce){\n"
    "    *{transition:none !important; animation:none !important}\n"
    "  }\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<aside id=\"sidebar\">\n"
    "  <div class=\"brand\">\n"
    "    <div class=\"logo\" aria-hidden=\"true\">c</div>\n"
    "    <div>\n"
    "      <h1>c-agent</h1>\n"
    "      <div class=\"sub\">Cognitive OS Runtime</div>\n"
    "    </div>\n"
    "  </div>\n"
    "  <nav id=\"nav\" aria-label=\"控制台分区\">\n"
    "    <button data-p=\"dashboard\" class=\"on\" aria-current=\"true\">\n"
    "      <svg viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><rect x=\"3\" y=\"3\" width=\"7\" height=\"7\"/><rect x=\"14\" y=\"3\" width=\"7\" height=\"7\"/><rect x=\"3\" y=\"14\" width=\"7\" height=\"7\"/><rect x=\"14\" y=\"14\" width=\"7\" height=\"7\"/></svg>\n"
    "      Dashboard\n"
    "    </button>\n"
    "    <button data-p=\"tasks\">\n"
    "      <svg viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><rect x=\"3\" y=\"4\" width=\"14\" height=\"16\" rx=\"2\"/><path d=\"m7.5 11 3 3 5-6\"/></svg>\n"
    "      Tasks\n"
    "    </button>\n"
    "    <button data-p=\"agents\">\n"
    "      <svg viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><path d=\"M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2\"/><circle cx=\"9\" cy=\"7\" r=\"4\"/><path d=\"M23 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75\"/></svg>\n"
    "      Agents\n"
    "    </button>\n"
    "    <button data-p=\"models\">\n"
    "      <svg viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\"/><rect x=\"9\" y=\"9\" width=\"6\" height=\"6\"/><path d=\"M9 1v3M15 1v3M9 20v3M15 20v3M1 9h3M1 15h3M20 9h3M20 15h3\"/></svg>\n"
    "      Models\n"
    "    </button>\n"
    "    <button data-p=\"mcp\">\n"
    "      <svg viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><path d=\"M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71\"/><path d=\"M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71\"/></svg>\n"
    "      MCP\n"
    "    </button>\n"
    "    <button data-p=\"skills\">\n"
    "      <svg viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><polyline points=\"4 17 10 11 4 5\"/><line x1=\"12\" y1=\"19\" x2=\"20\" y2=\"19\"/></svg>\n"
    "      Skills\n"
    "    </button>\n"
    "    <button data-p=\"plugins\">\n"
    "      <svg viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><path d=\"M21 12a7 7 0 1 1-7-7\"/><path d=\"M21 4v5h-5\"/></svg>\n"
    "      Plugins\n"
    "    </button>\n"
    "    <button data-p=\"im\">\n"
    "      <svg viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><path d=\"M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z\"/></svg>\n"
    "      IM\n"
    "    </button>\n"
    "    <button data-p=\"memory\">\n"
    "      <svg viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><ellipse cx=\"12\" cy=\"5\" rx=\"8\" ry=\"3\"/><path d=\"M4 5v14c0 1.66 3.58 3 8 3s8-1.34 8-3V5\"/><path d=\"M4 12c0 1.66 3.58 3 8 3s8-1.34 8-3\"/></svg>\n"
    "      Memory\n"
    "    </button>\n"
    "    <button data-p=\"snapshots\">\n"
    "      <svg viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><path d=\"M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z\"/><circle cx=\"12\" cy=\"13\" r=\"4\"/></svg>\n"
    "      Execution\n"
    "    </button>\n"
    "    <button data-p=\"trace\">\n"
    "      <svg viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><polyline points=\"22 12 18 12 15 21 9 3 6 12 2 12\"/></svg>\n"
    "      Monitor\n"
    "    </button>\n"
    "    <button data-p=\"cluster\">\n"
    "      <svg viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><rect x=\"9\" y=\"2\" width=\"6\" height=\"6\"/><rect x=\"2\" y=\"16\" width=\"6\" height=\"6\"/><rect x=\"16\" y=\"16\" width=\"6\" height=\"6\"/><path d=\"M12 8v5M8 16v-3a4 4 0 0 1 8 0v3\"/></svg>\n"
    "      Cluster\n"
    "    </button>\n"
    "    <button data-p=\"metrics\">\n"
    "      <svg viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><polyline points=\"23 6 13.5 15.5 8.5 10.5 1 18\"/><polyline points=\"17 6 23 6 23 12\"/></svg>\n"
    "      Metrics\n"
    "    </button>\n"
    "  </nav>\n"
    "  <div class=\"side-foot\">\n"
    "    <div class=\"conn\" role=\"status\" aria-live=\"polite\">\n"
    "      <span class=\"dot warn pulse\" id=\"connDot\"></span>\n"
    "      <span id=\"connText\">连接中…</span>\n"
    "    </div>\n"
    "  </div>\n"
    "</aside>\n"
    "<div class=\"backdrop\" id=\"backdrop\"></div>\n"
    "<main>\n"
    "  <div class=\"top\">\n"
    "    <div class=\"top-left\">\n"
    "      <button class=\"icon-btn\" id=\"navToggle\" aria-label=\"显示或隐藏菜单\" aria-expanded=\"false\">\n"
    "        <svg viewBox=\"0 0 24 24\" width=\"18\" height=\"18\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" aria-hidden=\"true\"><line x1=\"4\" y1=\"7\" x2=\"20\" y2=\"7\"/><line x1=\"4\" y1=\"12\" x2=\"20\" y2=\"12\"/><line x1=\"4\" y1=\"17\" x2=\"20\" y2=\"17\"/></svg>\n"
    "      </button>\n"
    "      <div class=\"title\" id=\"pageTitle\" tabindex=\"-1\">Dashboard</div>\n"
    "    </div>\n"
    "    <div class=\"topright\">\n"
    "      <span class=\"flow\">RECEIVE → UNDERSTAND → REASON → PLAN → ACT → VERIFY → LEARN</span>\n"
    "      <button class=\"icon-btn\" id=\"btnRefresh\" title=\"刷新当前页\" aria-label=\"刷新当前页\">\n"
    "        <svg viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><polyline points=\"23 4 23 10 17 10\"/><polyline points=\"1 20 1 14 7 14\"/><path d=\"M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15\"/></svg>\n"
    "      </button>\n"
    "      <select id=\"theme\" title=\"主题\">\n"
    "        <option value=\"dark\">Dark</option>\n"
    "        <option value=\"light\">Light</option>\n"
    "        <option value=\"ocean\">Ocean</option>\n"
    "        <option value=\"forest\">Forest</option>\n"
    "        <option value=\"sunset\">Sunset</option>\n"
    "      </select>\n"
    "    </div>\n"
    "  </div>\n"
    "  <div class=\"content\" id=\"content\"></div>\n"
    "</main>\n"
    "<div class=\"toast\" id=\"toast\" role=\"status\"></div>\n"
    "\n"
    "<script>\n"
    "'use strict';\n"
    "const $ = id => document.getElementById(id);\n"
    "\n"
    "/* ================= 基础工具 ================= */\n"
    "\n"
    "async function call(method, path, body) {\n"
    "  try {\n"
    "    const r = await fetch(path, {method, headers:{'Content-Type':'application/json'}, body: body ? JSON.stringify(body) : undefined});\n"
    "    const text = await r.text();\n"
    "    let obj; try { obj = JSON.parse(text); } catch { obj = {raw: text}; }\n"
    "    return {status: r.status, obj, text};\n"
    "  } catch (e) {\n"
    "    return {status: 0, obj: {error: String(e)}, text: ''};\n"
    "  }\n"
    "}\n"
    "\n"
    "function esc(s){ return String(s).replace(/[&<>\"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c])); }\n"
    "\n"
    "function renderPre(obj){ return jsonHighlight(obj); }\n"
    "\n"
    "function toast(msg){\n"
    "  const el = $('toast');\n"
    "  el.textContent = msg;\n"
    "  el.classList.add('show');\n"
    "  clearTimeout(toast._t);\n"
    "  toast._t = setTimeout(() => el.classList.remove('show'), 1600);\n"
    "}\n"
    "\n"
    "function copyText(t){\n"
    "  if(navigator.clipboard && navigator.clipboard.writeText){\n"
    "    navigator.clipboard.writeText(t).then(() => toast('已复制'), () => fallbackCopy(t));\n"
    "  } else fallbackCopy(t);\n"
    "}\n"
    "function fallbackCopy(t){\n"
    "  const ta = document.createElement('textarea');\n"
    "  ta.value = t; ta.style.position = 'fixed'; ta.style.opacity = '0';\n"
    "  document.body.appendChild(ta); ta.select();\n"
    "  try { document.execCommand('copy'); toast('已复制'); } catch(e) { toast('复制失败'); }\n"
    "  ta.remove();\n"
    "}\n"
    "function copyPre(id){ const el = $(id); if(el) copyText(el.textContent); }\n"
    "\n"
    "/* ================= JSON 语法高亮 ================= */\n"
    "\n"
    "const JSON_RX = /(\"(?:\\\\u[a-fA-F0-9]{4}|\\\\[^u]|[^\\\\\"])*\"(\\s*:)?|\\b(?:true|false|null)\\b|-?\\d+(?:\\.\\d+)?(?:[eE][+-]?\\d+)?)/g;\n"
    "\n"
    "function jsonHighlight(obj){\n"
    "  const s = JSON.stringify(obj, null, 2);\n"
    "  let out = '', last = 0, m;\n"
    "  JSON_RX.lastIndex = 0;\n"
    "  while ((m = JSON_RX.exec(s))) {\n"
    "    out += esc(s.slice(last, m.index));\n"
    "    const tok = m[0];\n"
    "    if (/:$/.test(tok)) {\n"
    "      out += '<span class=\"k\">' + esc(tok.slice(0, -1)) + '</span><span class=\"p\">:</span>';\n"
    "    } else if (tok[0] === '\"') {\n"
    "      out += '<span class=\"s\">' + esc(tok) + '</span>';\n"
    "    } else if (tok === 'true' || tok === 'false') {\n"
    "      out += '<span class=\"b\">' + tok + '</span>';\n"
    "    } else if (tok === 'null') {\n"
    "      out += '<span class=\"n\">null</span>';\n"
    "    } else {\n"
    "      out += '<span class=\"num\">' + tok + '</span>';\n"
    "    }\n"
    "    last = JSON_RX.lastIndex;\n"
    "  }\n"
    "  out += esc(s.slice(last));\n"
    "  return '<div class=\"json\">' + out + '</div>';\n"
    "}\n"
    "\n"
    "function renderJSON(obj, el){\n"
    "  if(!el) return;\n"
    "  const empty = obj == null ||\n"
    "    (Array.isArray(obj) && !obj.length) ||\n"
    "    (typeof obj === 'object' && !Array.isArray(obj) && !Object.keys(obj).length);\n"
    "  el.innerHTML = empty\n"
    "    ? '<div class=\"json\"><span class=\"empty\">（暂无数据）</span></div>'\n"
    "    : jsonHighlight(obj);\n"
    "}\n"
    "\n"
    "function outPanel(title, outId, pname){\n"
    "  return '<div class=\"card\"><div class=\"card-head\"><h2>' + esc(title) + '</h2>' +\n"
    "    '<div class=\"row\"><button class=\"sec sm\" onclick=\"load(\\'' + pname + '\\')\">Refresh</button>' +\n"
    "    '<button class=\"sec sm\" onclick=\"copyPre(\\'' + outId + '\\')\">Copy</button></div></div>' +\n"
    "    '<pre id=\"' + outId + '\">加载中…</pre></div>';\n"
    "}\n"
    "\n"
    "/* ================= 面板定义 ================= */\n"
    "\n"
    "const panels = {};\n"
    "\n"
    "panels.dashboard = `\n"
    "  <div class=\"stat-grid\" id=\"dashStats\">\n"
    "    <div class=\"stat\"><div class=\"num\">…</div><div class=\"lbl\">Version</div></div>\n"
    "    <div class=\"stat\"><div class=\"num\">…</div><div class=\"lbl\">Provider</div></div>\n"
    "    <div class=\"stat\"><div class=\"num\">…</div><div class=\"lbl\">Agents</div></div>\n"
    "    <div class=\"stat\"><div class=\"num\">…</div><div class=\"lbl\">Working memory</div></div>\n"
    "    <div class=\"stat\"><div class=\"num\">…</div><div class=\"lbl\">Plugins</div></div>\n"
    "    <div class=\"stat\"><div class=\"num\">…</div><div class=\"lbl\">IM messages</div></div>\n"
    "  </div>\n"
    "  <div class=\"card\">\n"
    "    <div class=\"card-head\">\n"
    "      <h2>Runtime status</h2>\n"
    "      <button class=\"sec sm\" onclick=\"loadDashboard()\">Refresh</button>\n"
    "    </div>\n"
    "    <pre id=\"dash-out\">加载中…</pre>\n"
    "  </div>`;\n"
    "\n"
    "panels.tasks = `\n"
    "  <div class=\"card\">\n"
    "    <h2>Run a task</h2>\n"
    "    <div class=\"hint\">提交一个自然语言任务，走完整 RECEIVE→UNDERSTAND→REASON→PLAN→ACT→VERIFY→LEARN 链路。</div>\n"
    "    <textarea id=\"prompt\" placeholder=\"例如：在 test/ 建文件 a.txt 并写入 hello\"></textarea>\n"
    "    <div class=\"row\">\n"
    "      <button onclick=\"runTask()\">Run</button>\n"
    "      <span id=\"taskstat\" class=\"muted\"></span>\n"
    "    </div>\n"
    "  </div>\n"
    "  <div class=\"card\">\n"
    "    <div class=\"card-head\"><h2>Recent tasks</h2></div>\n"
    "    <div class=\"chips\" id=\"histList\"></div>\n"
    "  </div>\n"
    "  <div class=\"card\">\n"
    "    <div class=\"card-head\">\n"
    "      <h2>Result</h2>\n"
    "      <button class=\"sec sm\" onclick=\"copyPre('out')\">Copy</button>\n"
    "    </div>\n"
    "    <pre id=\"out\">等待输入…</pre>\n"
    "  </div>`;\n"
    "\n"
    "panels.agents    = outPanel('Agent pool', 'agents-out', 'agents');\n"
    "panels.mcp       = outPanel('MCP connections', 'mcp-out', 'mcp');\n"
    "panels.memory    = outPanel('Memory (working / long-term)', 'memory-out', 'memory');\n"
    "panels.cluster   = outPanel('Cluster nodes', 'cluster-out', 'cluster');\n"
    "panels.metrics   = outPanel('Metrics (Prometheus)', 'metrics-out', 'metrics');\n"
    "\n"
    "panels.skills = `\n"
    "  <div class=\"card\">\n"
    "    <h2>Skills</h2>\n"
    "    <div class=\"hint\">静态 Shell/Python 技能，输入技能名即可运行。</div>\n"
    "    <div class=\"row\">\n"
    "      <input type=\"text\" id=\"skillname\" placeholder=\"技能名，例如 echo_hello\" style=\"flex:1;min-width:180px\">\n"
    "      <button onclick=\"runSkill()\">Run</button>\n"
    "    </div>\n"
    "  </div>\n"
    "  <div class=\"card\">\n"
    "    <div class=\"card-head\">\n"
    "      <h2>已注册技能</h2>\n"
    "      <button class=\"sec sm\" onclick=\"copyPre('skills-out')\">Copy</button>\n"
    "    </div>\n"
    "    <pre id=\"skills-out\">加载中…</pre>\n"
    "  </div>`;\n"
    "\n"
    "panels.plugins = `\n"
    "  <div class=\"card\">\n"
    "    <h2>⭐ Create plugin (AI 自生成)</h2>\n"
    "    <div class=\"hint\">描述一个能力需求，系统将走 需求分析→架构→代码生成→安全审计→注册→技能注入 的自进化闭环（真实 LLM 或离线模板）。</div>\n"
    "    <textarea id=\"plugin-desc\" placeholder=\"例如：增加自动分析 QEMU crash 日志的能力\"></textarea>\n"
    "    <div class=\"row\">\n"
    "      <button onclick=\"pluginGenerate()\">Generate</button>\n"
    "      <span id=\"plugin-stat\" class=\"muted\"></span>\n"
    "    </div>\n"
    "  </div>\n"
    "  <div class=\"card\">\n"
    "    <div class=\"card-head\">\n"
    "      <h2>Installed plugins</h2>\n"
    "      <button class=\"sec sm\" onclick=\"load('plugins')\">Refresh</button>\n"
    "    </div>\n"
    "    <pre id=\"plugins-out\">加载中…</pre>\n"
    "  </div>\n"
    "  <div class=\"card\">\n"
    "    <div class=\"card-head\">\n"
    "      <h2>生成结果</h2>\n"
    "      <button class=\"sec sm\" onclick=\"copyPre('plugin-result')\">Copy</button>\n"
    "    </div>\n"
    "    <pre id=\"plugin-result\">（生成后显示脚本）</pre>\n"
    "  </div>`;\n"
    "\n"
    "panels.snapshots = `\n"
    "  <div class=\"card\">\n"
    "    <h2>Execution snapshots</h2>\n"
    "    <div class=\"hint\">事务 + COW 快照：任务执行前记录文件状态，失败自动回滚。</div>\n"
    "    <div class=\"row\">\n"
    "      <button onclick=\"load('snapshots')\">Refresh</button>\n"
    "      <button class=\"sec danger\" onclick=\"rollback()\">Rollback latest</button>\n"
    "    </div>\n"
    "  </div>\n"
    "  <div class=\"card\">\n"
    "    <div class=\"card-head\">\n"
    "      <h2>快照列表</h2>\n"
    "      <button class=\"sec sm\" onclick=\"copyPre('snapshots-out')\">Copy</button>\n"
    "    </div>\n"
    "    <pre id=\"snapshots-out\">加载中…</pre>\n"
    "  </div>`;\n"
    "\n"
    "panels.trace = `\n"
    "  <div class=\"card\">\n"
    "    <div class=\"card-head\">\n"
    "      <h2>Trace (spans) · Monitor</h2>\n"
    "      <button class=\"sec sm\" onclick=\"load('trace')\">Refresh</button>\n"
    "    </div>\n"
    "    <pre id=\"trace-out\">加载中…</pre>\n"
    "  </div>`;\n"
    "\n"
    "panels.im = `\n"
    "  <div class=\"card\">\n"
    "    <div class=\"im-layout\">\n"
    "      <div>\n"
    "        <div class=\"row\" style=\"margin:0 0 8px\">\n"
    "          <input id=\"im-new\" type=\"text\" placeholder=\"会话名称\" style=\"flex:1\">\n"
    "          <button onclick=\"imCreate()\">＋</button>\n"
    "        </div>\n"
    "        <label class=\"toggle-row\" style=\"display:flex;align-items:center;gap:6px;margin:0 0 6px;font-size:12px;color:var(--muted)\">\n"
    "          <input type=\"checkbox\" id=\"im-group\" style=\"width:16px;height:16px;accent-color:var(--accent)\"> 群聊\n"
    "        </label>\n"
    "        <input id=\"im-members\" type=\"text\" placeholder=\"群成员（逗号分隔，如 alice,bob）\" style=\"margin-bottom:10px\" hidden>\n"
    "        <div class=\"im-sessions\" id=\"im-sessions\"></div>\n"
    "      </div>\n"
    "      <div>\n"
    "        <div class=\"row\" style=\"margin:0 0 8px\">\n"
    "          <input id=\"im-search\" type=\"text\" placeholder=\"搜索历史消息…\" style=\"flex:1\">\n"
    "          <button class=\"sec sm\" onclick=\"imSearch()\">Search</button>\n"
    "        </div>\n"
    "        <div id=\"im-search-results\"></div>\n"
    "        <div class=\"im-thread\" id=\"im-thread\">\n"
    "          <span class=\"muted\" style=\"font-size:12px\">选择一个会话开始聊天</span>\n"
    "        </div>\n"
    "        <div class=\"im-input-row\">\n"
    "          <input id=\"im-input\" type=\"text\" placeholder=\"消息内容，Enter 发送（@成员名 可指定发送者）\">\n"
    "          <button onclick=\"imSend()\">Send</button>\n"
    "        </div>\n"
    "      </div>\n"
    "    </div>\n"
    "  </div>`;\n"
    "\n"
    "panels.models = `\n"
    "  <div class=\"card\">\n"
    "    <h2>Model routes</h2>\n"
    "    <div class=\"hint\">管理 LLM 路由：点 <b>Set active</b> 把某条路由设为当前活跃模型（实时切换并持久化到 state/cagent.json）；<b>Delete</b> 移除一条路由。</div>\n"
    "    <div class=\"row\" style=\"margin-top:6px\">\n"
    "      <button onclick=\"loadModels()\">Refresh</button>\n"
    "      <span id=\"models-stat\" class=\"muted\"></span>\n"
    "    </div>\n"
    "    <div class=\"table-wrap\">\n"
    "      <table>\n"
    "        <thead><tr><th>Name</th><th>Provider</th><th>Model</th><th>Base URL</th><th>W</th><th>Calls</th><th></th></tr></thead>\n"
    "        <tbody id=\"routes-body\"><tr><td colspan=\"7\" class=\"muted\">加载中…</td></tr></tbody>\n"
    "      </table>\n"
    "    </div>\n"
    "  </div>\n"
    "  <div class=\"card\">\n"
    "    <h2>Add / update route</h2>\n"
    "    <div class=\"hint\">选择预设（DeepSeek / Ollama / Gemini / Groq / vLLM …）自动填充 base_url 与 model，也可手动填写任意 OpenAI 兼容端点。</div>\n"
    "    <div class=\"row\">\n"
    "      <input id=\"r-name\" type=\"text\" placeholder=\"name (如 deepseek)\" style=\"flex:1;min-width:140px\">\n"
    "      <select id=\"r-provider\" style=\"flex:0 0 auto\">\n"
    "        <option value=\"openai\">OpenAI</option>\n"
    "        <option value=\"anthropic\">Anthropic Claude</option>\n"
    "        <option value=\"deepseek\">DeepSeek（OpenAI 兼容）</option>\n"
    "        <option value=\"deepseek_a\">DeepSeek（Anthropic 端点）</option>\n"
    "        <option value=\"ollama\">Ollama（本地）</option>\n"
    "        <option value=\"gemini\">Gemini（OpenAI 兼容）</option>\n"
    "        <option value=\"groq\">Groq</option>\n"
    "        <option value=\"together\">Together AI</option>\n"
    "        <option value=\"vllm\">vLLM / llama.cpp（本地）</option>\n"
    "        <option value=\"mock\">mock（离线）</option>\n"
    "      </select>\n"
    "    </div>\n"
    "    <div class=\"row\">\n"
    "      <input id=\"r-model\" type=\"text\" placeholder=\"model (如 deepseek-chat)\" style=\"flex:2;min-width:180px\">\n"
    "      <input id=\"r-base\" type=\"text\" placeholder=\"base_url (如 https://api.deepseek.com/v1)\" style=\"flex:3;min-width:220px\">\n"
    "    </div>\n"
    "    <div class=\"row\">\n"
    "      <input id=\"r-key\" type=\"text\" placeholder=\"api_key\" style=\"flex:2;min-width:180px\">\n"
    "      <input id=\"r-weight\" type=\"text\" placeholder=\"weight (默认 1)\" value=\"1\" style=\"flex:1;min-width:80px\">\n"
    "    </div>\n"
    "    <div class=\"row\">\n"
    "      <button onclick=\"addRoute()\">Add route</button>\n"
    "      <span id=\"routes-msg\" class=\"muted\"></span>\n"
    "    </div>\n"
    "  </div>`;\n"
    "\n"
    "const fetchers = {\n"
    "  agents:    {path:'/v1/agents',    out:'agents-out'},\n"
    "  tools:     {path:'/v1/tools',     out:'tools-out'},\n"
    "  memory:    {path:'/v1/memory',    out:'memory-out'},\n"
    "  snapshots: {path:'/v1/snapshots', out:'snapshots-out'},\n"
    "  trace:     {path:'/v1/trace',     out:'trace-out'},\n"
    "  usage:     {path:'/v1/usage',     out:'usage-out'},\n"
    "  plugins:   {path:'/v1/plugins',   out:'plugins-out'},\n"
    "  skills:    {path:'/v1/skills',    out:'skills-out'},\n"
    "  mcp:       {path:'/v1/mcp',       out:'mcp-out'},\n"
    "  cluster:   {path:'/v1/cluster',   out:'cluster-out'},\n"
    "  metrics:   {path:'/metrics',      out:'metrics-out'},\n"
    "};\n"
    "\n"
    "/* ================= 数据加载 ================= */\n"
    "\n"
    "async function load(panel){\n"
    "  if(panel === 'models') return loadModels();\n"
    "  if(panel === 'dashboard') return loadDashboard();\n"
    "  if(panel === 'im') return renderIm();\n"
    "  if(panel === 'metrics'){\n"
    "    const r = await call('GET', '/metrics');\n"
    "    const el = $('metrics-out'); if(el) el.textContent = r.text;\n"
    "    return;\n"
    "  }\n"
    "  const f = fetchers[panel];\n"
    "  if(!f) return;\n"
    "  const r = await call('GET', f.path);\n"
    "  const el = $(f.out); if(el) renderJSON(r.obj, el);\n"
    "}\n"
    "\n"
    "async function loadDashboard(){\n"
    "  const [ag, mem, plg, im] = await Promise.all([\n"
    "    call('GET', '/v1/agents'),\n"
    "    call('GET', '/v1/memory'),\n"
    "    call('GET', '/v1/plugins'),\n"
    "    call('GET', '/v1/im/sessions'),\n"
    "  ]);\n"
    "  const st = $('dashStats');\n"
    "  if(st){\n"
    "    const agents  = Array.isArray(ag.obj) ? ag.obj.length : (ag.obj && ag.obj.agents ? ag.obj.agents.length : 0);\n"
    "    const wmem    = (mem.obj && Array.isArray(mem.obj.working)) ? mem.obj.working.length : 0;\n"
    "    const plugins = (plg.obj && plg.obj.plugins && Array.isArray(plg.obj.plugins)) ? plg.obj.plugins.length\n"
    "                  : (Array.isArray(plg.obj) ? plg.obj.length : 0);\n"
    "    const ims     = (im.obj && im.obj.total_messages) ? im.obj.total_messages : 0;\n"
    "    const cells = st.querySelectorAll('.stat .num');\n"
    "    if(cells.length >= 6){\n"
    "      cells[0].textContent = '0.1.0';\n"
    "      cells[1].textContent = 'mock';\n"
    "      cells[2].textContent = agents;\n"
    "      cells[3].textContent = wmem;\n"
    "      cells[4].textContent = plugins;\n"
    "      cells[5].textContent = ims;\n"
    "    }\n"
    "  }\n"
    "  const el = $('dash-out');\n"
    "  if(el){\n"
    "    const payload = {\n"
    "      agents: ag.obj, memory: mem.obj, plugins: plg.obj, im: im.obj\n"
    "    };\n"
    "    renderJSON(payload, el);\n"
    "  }\n"
    "}\n"
    "\n"
    "async function rollback(){\n"
    "  const r = await call('POST', '/v1/snapshots/rollback');\n"
    "  renderJSON(r.obj, $('snapshots-out'));\n"
    "  load('snapshots');\n"
    "}\n"
    "\n"
    "async function runSkill(){\n"
    "  const name = $('skillname').value.trim();\n"
    "  if(!name) return;\n"
    "  const r = await call('POST', '/v1/skills/run', {name});\n"
    "  renderJSON(r.obj, $('skills-out'));\n"
    "}\n"
    "\n"
    "/* ================= 插件自生成 ================= */\n"
    "\n"
    "async function pluginGenerate(){\n"
    "  const desc = $('plugin-desc').value.trim();\n"
    "  const st = $('plugin-stat');\n"
    "  if(!desc){ if(st) st.textContent = '请输入能力描述'; return; }\n"
    "  if(st) st.textContent = '生成中…（分析→架构→生成→安全审计→注册）';\n"
    "  const r = await call('POST', '/v1/plugins/generate', {description: desc});\n"
    "  if(st) st.textContent = (r.obj && r.obj.ok) ? '✔ 已生成并注册' : ((r.obj && r.obj.error) ? 'error: ' + r.obj.error : 'error ' + r.status);\n"
    "  renderJSON(r.obj, $('plugin-result'));\n"
    "  if(r.obj && r.obj.ok) load('plugins');\n"
    "}\n"
    "\n"
    "/* ================= IM ================= */\n"
    "\n"
    "let IM_ACTIVE = null;\n"
    "let WS = null;\n"
    "\n"
    "function imCreate(){\n"
    "  const name = $('im-new').value.trim() || '新会话';\n"
    "  const isGroup = $('im-group').checked;\n"
    "  const members = $('im-members').value.split(',').map(s => s.trim()).filter(Boolean);\n"
    "  const body = {name: name, kind: isGroup ? 'group' : 'direct'};\n"
    "  if(members.length) body.members = members;\n"
    "  call('POST', '/v1/im/sessions', body).then(() => {\n"
    "    $('im-new').value = ''; $('im-members').value = '';\n"
    "    renderIm();\n"
    "  });\n"
    "}\n"
    "\n"
    "function imDelete(id){\n"
    "  call('DELETE', '/v1/im/sessions/' + id).then(() => {\n"
    "    if(IM_ACTIVE === id) IM_ACTIVE = null;\n"
    "    renderIm();\n"
    "  });\n"
    "}\n"
    "\n"
    "function imSelect(id){\n"
    "  IM_ACTIVE = id;\n"
    "  document.querySelectorAll('.im-session').forEach(s => s.classList.toggle('on', s.dataset.id === String(id)));\n"
    "  renderImThread();\n"
    "}\n"
    "\n"
    "function appendImMessage(m){\n"
    "  const t = $('im-thread');\n"
    "  if(!t) return;\n"
    "  const d = new Date(m.ts_ms || Date.now());\n"
    "  const time = d.getHours() + ':' + String(d.getMinutes()).padStart(2, '0');\n"
    "  const isMine = (m.role === 'user') && (!m.sender || m.sender === 'me');\n"
    "  const div = document.createElement('div');\n"
    "  div.className = 'im-msg ' + (isMine ? 'user' : 'assistant');\n"
    "  div.textContent = m.content || '';\n"
    "  const meta = document.createElement('div');\n"
    "  meta.className = 'meta';\n"
    "  const who = m.sender || (m.role === 'user' ? 'user' : 'assistant');\n"
    "  meta.textContent = who + ' · ' + time;\n"
    "  div.appendChild(meta);\n"
    "  t.appendChild(div);\n"
    "  t.scrollTop = t.scrollHeight;\n"
    "}\n"
    "\n"
    "async function renderImThread(){\n"
    "  const t = $('im-thread');\n"
    "  if(!t) return;\n"
    "  if(IM_ACTIVE === null){\n"
    "    t.innerHTML = '<span class=\"muted\" style=\"font-size:12px\">选择一个会话开始聊天</span>';\n"
    "    return;\n"
    "  }\n"
    "  t.innerHTML = '<span class=\"muted\"><span class=\"spin\"></span> 加载中…</span>';\n"
    "  const r = await call('GET', '/v1/im/sessions/' + IM_ACTIVE + '/messages');\n"
    "  t.innerHTML = '';\n"
    "  if(Array.isArray(r.obj)){\n"
    "    r.obj.forEach(m => appendImMessage(m));\n"
    "  }\n"
    "}\n"
    "\n"
    "async function renderIm(){\n"
    "  const list = $('im-sessions');\n"
    "  if(!list) return;\n"
    "  const g = $('im-group');\n"
    "  if(g && !g.dataset.bound){\n"
    "    g.dataset.bound = '1';\n"
    "    g.addEventListener('change', () => { const el = $('im-members'); if(el) el.hidden = !g.checked; });\n"
    "  }\n"
    "  const r = await call('GET', '/v1/im/sessions');\n"
    "  const sessions = (r.obj && Array.isArray(r.obj.sessions)) ? r.obj.sessions : [];\n"
    "  list.innerHTML = '';\n"
    "  if(!sessions.length){\n"
    "    list.innerHTML = '<span class=\"muted\" style=\"font-size:12px\">暂无会话，创建第一个吧</span>';\n"
    "    return;\n"
    "  }\n"
    "  sessions.forEach(s => {\n"
    "    const isGroup = s.kind === 'group';\n"
    "    const div = document.createElement('div');\n"
    "    div.className = 'im-session' + (s.id === IM_ACTIVE ? ' on' : '');\n"
    "    div.dataset.id = s.id;\n"
    "    div.onclick = () => imSelect(s.id);\n"
    "    const name = document.createElement('span');\n"
    "    name.className = 'name';\n"
    "    name.textContent = (s.name || ('#' + s.id)) + ' · ' + (s.messages || 0);\n"
    "    if(isGroup) name.textContent += ' · ' + ((s.members || []).length) + '人';\n"
    "    const badge = document.createElement('span');\n"
    "    badge.className = 'badge ' + (isGroup ? 'badge-ok' : 'badge-warn');\n"
    "    badge.textContent = isGroup ? '群' : '单';\n"
    "    const del = document.createElement('button');\n"
    "    del.className = 'del';\n"
    "    del.textContent = '✕';\n"
    "    del.title = '删除会话';\n"
    "    del.onclick = (e) => { e.stopPropagation(); imDelete(s.id); };\n"
    "    const left = document.createElement('span');\n"
    "    left.style.cssText = 'display:flex;align-items:center;gap:6px;min-width:0;flex:1';\n"
    "    left.appendChild(badge);\n"
    "    left.appendChild(name);\n"
    "    div.appendChild(left);\n"
    "    div.appendChild(del);\n"
    "    list.appendChild(div);\n"
    "  });\n"
    "  renderImThread();\n"
    "}\n"
    "\n"
    "function imSend(){\n"
    "  const input = $('im-input');\n"
    "  let content = input.value.trim();\n"
    "  if(!content || IM_ACTIVE === null) return;\n"
    "  let sender = 'me';\n"
    "  const m = content.match(/^@(\\S+)\\s+/);\n"
    "  if(m){ sender = m[1]; content = content.slice(m[0].length); }\n"
    "  if(!content) return;\n"
    "  input.value = '';\n"
    "  const payload = {type:'im.send', session_id: IM_ACTIVE, content, sender};\n"
    "  if(WS && WS.readyState === WebSocket.OPEN){\n"
    "    WS.send(JSON.stringify(payload));\n"
    "  } else {\n"
    "    call('POST', '/v1/im/sessions/' + IM_ACTIVE + '/messages', {role:'user', content, sender}).then(r => {\n"
    "      if(r.obj && r.obj.ok) renderImThread();\n"
    "    });\n"
    "  }\n"
    "}\n"
    "\n"
    "async function imSearch(){\n"
    "  const q = $('im-search').value.trim();\n"
    "  const box = $('im-search-results');\n"
    "  if(!q){ if(box) box.innerHTML = ''; return; }\n"
    "  const r = await call('GET', '/v1/im/search?q=' + encodeURIComponent(q));\n"
    "  const hits = Array.isArray(r.obj) ? r.obj : [];\n"
    "  if(!box) return;\n"
    "  if(!hits.length){\n"
    "    box.innerHTML = '<div class=\"muted\" style=\"font-size:12px;margin:0 0 8px\">无匹配</div>';\n"
    "    return;\n"
    "  }\n"
    "  box.innerHTML = '<div class=\"chips\" style=\"margin-bottom:8px\">' + hits.map(h =>\n"
    "    '<button class=\"chip\" onclick=\"imSelect(' + h.session_id + ')\" title=\"' + esc(h.content) + '\">' +\n"
    "    '<b>' + esc(h.session_name || ('#' + h.session_id)) + '</b><span>' + esc(h.content) + '</span></button>'\n"
    "  ).join('') + '</div>';\n"
    "}\n"
    "\n"
    "/* ================= WebSocket 实时推送 ================= */\n"
    "\n"
    "function wsConnect(){\n"
    "  try {\n"
    "    const proto = location.protocol === 'https:' ? 'wss' : 'ws';\n"
    "    WS = new WebSocket(proto + '://' + location.host + '/ws');\n"
    "    WS.onmessage = (e) => {\n"
    "      try {\n"
    "        const m = JSON.parse(e.data);\n"
    "        if(m.type === 'im.message'){\n"
    "          if(current === 'im' && IM_ACTIVE === m.session_id){\n"
    "            appendImMessage(m);\n"
    "          } else {\n"
    "            toast('📩 新消息: ' + ((m.role === 'user') ? '用户' : '助手'));\n"
    "          }\n"
    "        }\n"
    "      } catch(err) { /* ignore non-JSON */ }\n"
    "    };\n"
    "    WS.onclose = () => { setTimeout(wsConnect, 3000); };\n"
    "    WS.onerror = () => { try { WS.close(); } catch(e) {} };\n"
    "  } catch(e) { /* ws unsupported */ }\n"
    "}\n"
    "\n"
    "/* ================= 任务 ================= */\n"
    "\n"
    "let TASK_HIST = [];\n"
    "try { TASK_HIST = JSON.parse(localStorage.getItem('cagent-task-hist') || '[]'); } catch(e) { TASK_HIST = []; }\n"
    "\n"
    "function addHist(id, prompt){\n"
    "  TASK_HIST.unshift({id, prompt: String(prompt).slice(0, 60), t: Date.now()});\n"
    "  TASK_HIST = TASK_HIST.slice(0, 12);\n"
    "  try { localStorage.setItem('cagent-task-hist', JSON.stringify(TASK_HIST)); } catch(e) {}\n"
    "  renderHist();\n"
    "}\n"
    "\n"
    "function renderHist(){\n"
    "  const el = $('histList'); if(!el) return;\n"
    "  if(!TASK_HIST.length){\n"
    "    el.innerHTML = '<span class=\"muted\" style=\"font-size:12px\">暂无历史任务</span>';\n"
    "    return;\n"
    "  }\n"
    "  el.innerHTML = TASK_HIST.map(h =>\n"
    "    '<button class=\"chip\" onclick=\"viewHist(' + h.id + ')\" title=\"' + esc(h.prompt) + '\">' +\n"
    "    '<b>#' + h.id + '</b><span>' + esc(h.prompt) + '</span></button>'\n"
    "  ).join('');\n"
    "}\n"
    "\n"
    "async function viewHist(id){\n"
    "  const st = $('taskstat'); if(st) st.textContent = 'loading #' + id + '…';\n"
    "  const r = await call('GET', '/v1/tasks/' + id);\n"
    "  renderJSON(r.obj, $('out'));\n"
    "  if(st) st.textContent = (r.obj && r.obj.status) || '';\n"
    "}\n"
    "\n"
    "async function runTask(){\n"
    "  const prompt = $('prompt').value.trim();\n"
    "  if(!prompt) return;\n"
    "  const st = $('taskstat'); if(st) st.textContent = 'submitting…';\n"
    "  const c = await call('POST', '/v1/tasks', {prompt});\n"
    "  const id = c.obj && c.obj.id;\n"
    "  if(id === undefined){\n"
    "    renderJSON(c.obj, $('out'));\n"
    "    if(st) st.textContent = '';\n"
    "    return;\n"
    "  }\n"
    "  addHist(id, prompt);\n"
    "  for(let i = 0; i < 120; i++){\n"
    "    const r = await call('GET', '/v1/tasks/' + id);\n"
    "    renderJSON(r.obj, $('out'));\n"
    "    const taskStatus = r.obj.status;\n"
    "    if(st) st.textContent = taskStatus || '';\n"
    "    if(taskStatus === 'DONE' || taskStatus === 'FAILED' || taskStatus === 'CANCELLED' || taskStatus === 'TIMEOUT') return;\n"
    "    await new Promise(res => setTimeout(res, 300));\n"
    "  }\n"
    "}\n"
    "\n"
    "/* ================= 模型路由 ================= */\n"
    "\n"
    "const PROVIDER_PRESETS = {\n"
    "  mock:      {provider:'mock',      base:'',                                                                 model:''},\n"
    "  openai:    {provider:'openai',    base:'https://api.openai.com/v1',                                        model:'gpt-4o'},\n"
    "  anthropic: {provider:'anthropic', base:'https://api.anthropic.com',                                        model:'claude-sonnet-4-6'},\n"
    "  deepseek:  {provider:'openai',    base:'https://api.deepseek.com/v1',                                      model:'deepseek-chat'},\n"
    "  deepseek_a:{provider:'anthropic', base:'https://api.deepseek.com/anthropic',                               model:'deepseek-v4-pro'},\n"
    "  ollama:    {provider:'openai',    base:'http://localhost:11434/v1',                                        model:'llama3'},\n"
    "  gemini:    {provider:'openai',    base:'https://generativelanguage.googleapis.com/v1beta/openai',          model:'gemini-2.0-flash'},\n"
    "  groq:      {provider:'openai',    base:'https://api.groq.com/openai/v1',                                   model:'llama-3.3-70b-versatile'},\n"
    "  together:  {provider:'openai',    base:'https://api.together.xyz/v1',                                      model:'meta-llama/Llama-3.3-70B-Instruct-Turbo'},\n"
    "  vllm:      {provider:'openai',    base:'http://localhost:8080/v1',                                         model:''},\n"
    "};\n"
    "\n"
    "function presetProvider(){\n"
    "  return (PROVIDER_PRESETS[$('r-provider').value] || PROVIDER_PRESETS.openai).provider;\n"
    "}\n"
    "\n"
    "let ROUTES = [];\n"
    "let ACTIVE = {provider:'', model:'', api_key_set:false};\n"
    "\n"
    "async function loadModels(){\n"
    "  const r   = await call('GET', '/v1/routes');\n"
    "  const cfg = await call('GET', '/v1/config/llm');\n"
    "  ROUTES = Array.isArray(r.obj) ? r.obj : [];\n"
    "  ACTIVE = (cfg.obj && typeof cfg.obj === 'object') ? cfg.obj : ACTIVE;\n"
    "  const rp = $('r-provider');\n"
    "  if(rp && !rp.dataset.bound){\n"
    "    rp.dataset.bound = '1';\n"
    "    rp.addEventListener('change', () => {\n"
    "      const p = PROVIDER_PRESETS[$('r-provider').value] || PROVIDER_PRESETS.openai;\n"
    "      const rb = $('r-base'), rm = $('r-model');\n"
    "      if(rb) rb.value = p.base;\n"
    "      if(rm){ rm.placeholder = p.model || 'model (可选)'; if(!rm.value) rm.value = p.model; }\n"
    "    });\n"
    "  }\n"
    "  const st = $('models-stat');\n"
    "  if(st) st.textContent = 'active: ' + (ACTIVE.provider || '?')\n"
    "      + (ACTIVE.model ? ' / ' + ACTIVE.model : '')\n"
    "      + (ACTIVE.api_key_set ? '' : '（未配置 api_key）');\n"
    "  const t = $('routes-body');\n"
    "  if(!t) return;\n"
    "  if(!ROUTES.length){ t.innerHTML = '<tr><td colspan=\"7\" class=\"muted\">（暂无路由）</td></tr>'; return; }\n"
    "  const ap = ACTIVE.provider || '';\n"
    "  t.innerHTML = ROUTES.map((x, i) => {\n"
    "    const isActive = x.name === ap;\n"
    "    return '<tr class=\"' + (isActive ? 'active-row' : '') + '\">'\n"
    "      + '<td>' + esc(x.name || '') + (isActive ? ' <span class=\"badge badge-ok\">active</span>' : '') + '</td>'\n"
    "      + '<td>' + esc(x.provider || '') + '</td>'\n"
    "      + '<td>' + esc(x.model || '') + '</td>'\n"
    "      + '<td class=\"muted\">' + esc(x.base_url || '') + '</td>'\n"
    "      + '<td>' + (x.weight != null ? x.weight : 1) + '</td>'\n"
    "      + '<td>' + (x.calls != null ? x.calls : 0) + '</td>'\n"
    "      + '<td><button onclick=\"setActive(' + i + ')\" class=\"sec sm\"' + (isActive ? ' disabled' : '') + '>Set active</button> '\n"
    "      + '<button onclick=\"deleteRoute(' + i + ')\" class=\"sec sm danger\">Delete</button></td></tr>';\n"
    "  }).join('');\n"
    "}\n"
    "\n"
    "async function setActive(i){\n"
    "  const x = ROUTES[i]; if(!x) return;\n"
    "  const st = $('models-stat'); if(st) st.textContent = 'switching…';\n"
    "  const r = await call('POST', '/v1/config/llm', {\n"
    "    provider: x.provider, base_url: x.base_url || '', model: x.model || '', api_key: x.api_key || ''\n"
    "  });\n"
    "  if(st) st.textContent = (r.obj && r.obj.ok)\n"
    "      ? 'switched to ' + (x.model || x.provider)\n"
    "      : (r.obj && r.obj.error) ? 'error: ' + r.obj.error : 'error ' + r.status;\n"
    "  loadModels();\n"
    "}\n"
    "\n"
    "async function deleteRoute(i){\n"
    "  const x = ROUTES[i]; if(!x) return;\n"
    "  await call('DELETE', '/v1/routes/' + encodeURIComponent(x.name));\n"
    "  loadModels();\n"
    "}\n"
    "\n"
    "async function addRoute(){\n"
    "  const name = $('r-name').value.trim();\n"
    "  const provider = presetProvider();\n"
    "  const msg = $('routes-msg');\n"
    "  if(!name){ if(msg) msg.textContent = 'need name'; return; }\n"
    "  const body = {\n"
    "    name, provider,\n"
    "    base_url: $('r-base').value.trim(),\n"
    "    model: $('r-model').value.trim(),\n"
    "    api_key: $('r-key').value.trim()\n"
    "  };\n"
    "  const w = parseFloat($('r-weight').value);\n"
    "  if(!isNaN(w)) body.weight = w;\n"
    "  const r = await call('POST', '/v1/routes', body);\n"
    "  if(msg) msg.textContent = (r.status < 300) ? 'route saved'\n"
    "      : (r.obj && r.obj.error) ? 'error: ' + r.obj.error : 'error ' + r.status;\n"
    "  if(r.status < 300){\n"
    "    $('r-name').value = ''; $('r-base').value = ''; $('r-key').value = ''; $('r-model').value = '';\n"
    "  }\n"
    "  loadModels();\n"
    "}\n"
    "\n"
    "/* ================= 导航 ================= */\n"
    "\n"
    "const TITLES = {dashboard:'Dashboard', tasks:'Tasks', agents:'Agents', models:'Models', mcp:'MCP', skills:'Skills', plugins:'Plugins', im:'IM', memory:'Memory', snapshots:'Execution', trace:'Monitor', cluster:'Cluster', metrics:'Metrics'};\n"
    "let current = 'dashboard';\n"
    "\n"
    "function switchPanel(p){\n"
    "  current = p;\n"
    "  document.querySelectorAll('#nav button').forEach(b => {\n"
    "    const on = b.dataset.p === p;\n"
    "    b.classList.toggle('on', on);\n"
    "    if(on) b.setAttribute('aria-current', 'true'); else b.removeAttribute('aria-current');\n"
    "  });\n"
    "  const t = $('pageTitle'); if(t) t.textContent = TITLES[p] || p;\n"
    "  $('content').innerHTML = panels[p];\n"
    "  if(p === 'tasks'){ renderHist(); return; }\n"
    "  load(p);\n"
    "  if(window.innerWidth < 900) toggleSidebar(false);\n"
    "}\n"
    "\n"
    "document.querySelectorAll('#nav button').forEach(b => {\n"
    "  b.addEventListener('click', () => switchPanel(b.dataset.p));\n"
    "});\n"
    "\n"
    "function toggleSidebar(force){\n"
    "  const open = typeof force === 'boolean' ? force : !$('sidebar').classList.contains('open');\n"
    "  $('sidebar').classList.toggle('open', open);\n"
    "  $('navToggle').setAttribute('aria-expanded', open ? 'true' : 'false');\n"
    "  $('backdrop').classList.toggle('on', open && window.innerWidth < 900);\n"
    "}\n"
    "$('navToggle').addEventListener('click', () => toggleSidebar());\n"
    "$('backdrop').addEventListener('click', () => toggleSidebar(false));\n"
    "\n"
    "$('btnRefresh').addEventListener('click', () => {\n"
    "  if(current === 'tasks'){ toast('已在 Tasks 页'); return; }\n"
    "  if(current === 'models') loadModels(); else load(current);\n"
    "  toast('已刷新');\n"
    "});\n"
    "\n"
    "/* ================= 主题 ================= */\n"
    "\n"
    "const THEMES = ['dark', 'light', 'ocean', 'forest', 'sunset'];\n"
    "function applyTheme(t){\n"
    "  if(!THEMES.includes(t)) t = 'dark';\n"
    "  document.body.dataset.theme = t;\n"
    "  try { localStorage.setItem('cagent-theme', t); } catch(e) {}\n"
    "  const sel = $('theme'); if(sel) sel.value = t;\n"
    "}\n"
    "$('theme').addEventListener('change', e => applyTheme(e.target.value));\n"
    "applyTheme(localStorage.getItem('cagent-theme') || 'dark');\n"
    "\n"
    "/* ================= 连接状态 ================= */\n"
    "\n"
    "async function pingServer(){\n"
    "  const r = await call('GET', '/v1/config/llm');\n"
    "  const ok = r.status !== 0;\n"
    "  const dot = $('connDot'), txt = $('connText');\n"
    "  if(dot){ dot.className = 'dot ' + (ok ? 'ok' : 'err'); }\n"
    "  if(txt) txt.textContent = ok ? '已连接' : '离线';\n"
    "}\n"
    "setInterval(pingServer, 8000);\n"
    "\n"
    "/* ================= 初始化 ================= */\n"
    "\n"
    "$('content').innerHTML = panels.dashboard;\n"
    "$('prompt').addEventListener('keydown', e => {\n"
    "  if(e.key === 'Enter' && (e.ctrlKey || e.metaKey)) runTask();\n"
    "});\n"
    "const imInput = $('im-input');\n"
    "if(imInput) imInput.addEventListener('keydown', e => { if(e.key === 'Enter') imSend(); });\n"
    "renderHist();\n"
    "pingServer();\n"
    "wsConnect();\n"
    "loadDashboard();\n"
    "</script>\n"
    "</body>\n"
    "</html>\n"
    "\n"
    ;
