/* web_ui.h — GENERATED from apps/web/index.html by tools/gen_web_ui.py.
 * Do not edit by hand; re-run the generator after changing the HTML. */
#pragma once
static const char ca_web_index_html[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"zh\">\n"
    "<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "<title>c-agent — Cognitive OS Console</title>\n"
    "<style>\n"
    "  :root{--bg:#0f1115;--card:#171a21;--border:#262b36;--fg:#e6e6e6;--muted:#8a93a3;--accent:#2f6feb;--ok:#4ade80;--warn:#ffd166}\n"
    "  *{box-sizing:border-box}\n"
    "  body{font-family:system-ui,Segoe UI,Roboto,sans-serif;background:var(--bg);color:var(--fg);margin:0;display:flex;height:100vh;overflow:hidden}\n"
    "  aside{width:210px;background:#0b0d11;border-right:1px solid var(--border);padding:16px 0;display:flex;flex-direction:column;flex-shrink:0}\n"
    "  aside h1{font-size:15px;margin:0 16px 4px}\n"
    "  aside .sub{color:var(--muted);font-size:11px;margin:0 16px 16px}\n"
    "  nav{flex:1;overflow-y:auto}\n"
    "  nav button{display:block;width:100%;text-align:left;background:none;border:0;color:var(--fg);padding:9px 16px;font-size:13px;cursor:pointer}\n"
    "  nav button:hover{background:#14171d}\n"
    "  nav button.on{background:#1a1f2b;border-left:3px solid var(--accent);color:#fff}\n"
    "  main{flex:1;display:flex;flex-direction:column;min-width:0}\n"
    "  .top{display:flex;align-items:center;justify-content:space-between;padding:14px 20px;border-bottom:1px solid var(--border)}\n"
    "  .top .title{font-size:14px;font-weight:600}\n"
    "  .top .flow{color:var(--muted);font-size:11px;letter-spacing:.5px}\n"
    "  .content{flex:1;padding:20px;overflow-y:auto}\n"
    "  .card{background:var(--card);border:1px solid var(--border);border-radius:8px;padding:14px;margin-bottom:14px}\n"
    "  .card h2{font-size:13px;margin:0 0 10px;color:var(--fg)}\n"
    "  .hint{color:var(--muted);font-size:12px;margin:4px 0 10px}\n"
    "  textarea,input[type=text]{width:100%;background:var(--bg);color:var(--fg);border:1px solid #2c3340;border-radius:6px;padding:8px;font-family:ui-monospace,Consolas,monospace;font-size:13px}\n"
    "  textarea{height:64px}\n"
    "  .row{display:flex;gap:8px;align-items:center;margin-top:8px;flex-wrap:wrap}\n"
    "  button{background:var(--accent);color:#fff;border:0;border-radius:6px;padding:8px 14px;font-size:13px;cursor:pointer}\n"
    "  button.sec{background:var(--card);border:1px solid var(--border);color:var(--fg)}\n"
    "  button:disabled{opacity:.5;cursor:not-allowed}\n"
    "  pre{background:var(--bg);border:1px solid var(--border);border-radius:6px;padding:10px;font-size:12px;overflow:auto;white-space:pre-wrap;word-break:break-word;max-height:50vh;min-height:60px;margin:0}\n"
    "  .badge-ok{color:var(--ok)} .badge-warn{color:var(--warn)}\n"
    "  table{width:100%;border-collapse:collapse;font-size:12px}\n"
    "  th,td{text-align:left;padding:6px 8px;border-bottom:1px solid var(--border)}\n"
    "  th{color:var(--muted);font-weight:600}\n"
    "  .muted{color:var(--muted)}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<aside>\n"
    "  <h1>c-agent</h1>\n"
    "  <div class=\"sub\">Cognitive OS Runtime</div>\n"
    "  <nav id=\"nav\">\n"
    "    <button data-p=\"tasks\" class=\"on\">Tasks</button>\n"
    "    <button data-p=\"tools\">Tools</button>\n"
    "    <button data-p=\"memory\">Memory</button>\n"
    "    <button data-p=\"snapshots\">Snapshots</button>\n"
    "    <button data-p=\"trace\">Trace</button>\n"
    "    <button data-p=\"models\">Models</button>\n"
    "    <button data-p=\"usage\">Usage</button>\n"
    "    <button data-p=\"plugins\">Plugins</button>\n"
    "    <button data-p=\"skills\">Skills</button>\n"
    "    <button data-p=\"mcp\">MCP</button>\n"
    "    <button data-p=\"cluster\">Cluster</button>\n"
    "    <button data-p=\"metrics\">Metrics</button>\n"
    "  </nav>\n"
    "</aside>\n"
    "\n"
    "<main>\n"
    "  <div class=\"top\">\n"
    "    <div class=\"title\">Console</div>\n"
    "    <div class=\"flow\">RECEIVE → UNDERSTAND → REASON → PLAN → ACT → VERIFY → LEARN</div>\n"
    "  </div>\n"
    "  <div class=\"content\" id=\"content\"></div>\n"
    "</main>\n"
    "\n"
    "<script>\n"
    "const $ = id => document.getElementById(id);\n"
    "\n"
    "async function call(method, path, body) {\n"
    "  try {\n"
    "    const r = await fetch(path, {method, headers:{'Content-Type':'application/json'}, body: body ? JSON.stringify(body) : undefined});\n"
    "    const text = await r.text();\n"
    "    let obj; try { obj = JSON.parse(text); } catch { obj = {raw: text}; }\n"
    "    return {status: r.status, obj, text};\n"
    "  } catch (e) {\n"
    "    return {status: 0, obj: {error: String(e)}, text: ''};\n"
    "  }\n"
    "}\n"
    "\n"
    "function esc(s){ return String(s).replace(/[&<>\"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c])); }\n"
    "\n"
    "function renderPre(obj){\n"
    "  return '<div class=\"card\"><h2>Output</h2><pre>' + esc(JSON.stringify(obj, null, 2)) + '</pre></div>';\n"
    "}\n"
    "\n"
    "/* ---- panels ---- */\n"
    "const panels = {};\n"
    "\n"
    "panels.tasks = `\n"
    "  <div class=\"card\">\n"
    "    <h2>Run a task</h2>\n"
    "    <div class=\"hint\">提交一个自然语言任务，走完整 RECEIVE→…→LEARN 链路。</div>\n"
    "    <textarea id=\"prompt\" placeholder=\"例如：在 test/ 建文件 a.txt 并写入 hello\"></textarea>\n"
    "    <div class=\"row\">\n"
    "      <button onclick=\"runTask()\">Run</button>\n"
    "      <span id=\"taskstat\" class=\"muted\"></span>\n"
    "    </div>\n"
    "  </div>\n"
    "  <div class=\"card\"><h2>Result</h2><pre id=\"out\">等待输入…</pre></div>`;\n"
    "\n"
    "async function runTask(){\n"
    "  const prompt = $('prompt').value.trim();\n"
    "  if(!prompt) return;\n"
    "  $('taskstat').textContent = 'submitting…';\n"
    "  const c = await call('POST','/v1/tasks',{prompt});\n"
    "  const id = c.obj && c.obj.id;\n"
    "  if(id === undefined){ $('out').textContent = JSON.stringify(c.obj,null,2); $('taskstat').textContent=''; return; }\n"
    "  for(let i=0;i<120;i++){\n"
    "    const r = await call('GET','/v1/tasks/'+id);\n"
    "    $('out').textContent = JSON.stringify(r.obj,null,2);\n"
    "    const st = r.obj.status;\n"
    "    $('taskstat').textContent = st || '';\n"
    "    if(st==='DONE'||st==='FAILED'||st==='CANCELLED'||st==='TIMEOUT') return;\n"
    "    await new Promise(res=>setTimeout(res,300));\n"
    "  }\n"
    "}\n"
    "\n"
    "panels.tools = '<div class=\"card\"><h2>Tools</h2><pre id=\"tools-out\">加载中…</pre></div>';\n"
    "panels.memory = '<div class=\"card\"><h2>Memory</h2><pre id=\"memory-out\">加载中…</pre></div>';\n"
    "panels.snapshots = `\n"
    "  <div class=\"card\"><h2>Snapshots</h2>\n"
    "    <div class=\"row\"><button onclick=\"load('snapshots')\">Refresh</button>\n"
    "    <button class=\"sec\" onclick=\"rollback()\">Rollback latest</button></div>\n"
    "  </div>\n"
    "  <div class=\"card\"><pre id=\"snapshots-out\">加载中…</pre></div>`;\n"
    "panels.trace = '<div class=\"card\"><h2>Trace (spans)</h2><pre id=\"trace-out\">加载中…</pre></div>';\n"
    "panels.models = '<div class=\"card\"><h2>Model routes</h2><pre id=\"models-out\">加载中…</pre></div>';\n"
    "panels.usage = '<div class=\"card\"><h2>Token usage</h2><pre id=\"usage-out\">加载中…</pre></div>';\n"
    "panels.plugins = '<div class=\"card\"><h2>Plugin registry</h2><pre id=\"plugins-out\">加载中…</pre></div>';\n"
    "panels.skills = `\n"
    "  <div class=\"card\"><h2>Skills</h2>\n"
    "    <div class=\"hint\">静态 Shell/Python 技能。</div>\n"
    "    <div class=\"row\">\n"
    "      <input type=\"text\" id=\"skillname\" placeholder=\"技能名，例如 echo_hello\" style=\"flex:1;min-width:180px\">\n"
    "      <button onclick=\"runSkill()\">Run</button>\n"
    "    </div>\n"
    "  </div>\n"
    "  <div class=\"card\"><pre id=\"skills-out\">加载中…</pre></div>`;\n"
    "panels.mcp = '<div class=\"card\"><h2>MCP connections</h2><pre id=\"mcp-out\">加载中…</pre></div>';\n"
    "panels.cluster = '<div class=\"card\"><h2>Cluster nodes</h2><pre id=\"cluster-out\">加载中…</pre></div>';\n"
    "panels.metrics = '<div class=\"card\"><h2>Metrics</h2><pre id=\"metrics-out\">加载中…</pre></div>';\n"
    "\n"
    "const fetchers = {\n"
    "  tools:     {path:'/v1/tools',     out:'tools-out'},\n"
    "  memory:    {path:'/v1/memory',    out:'memory-out'},\n"
    "  snapshots: {path:'/v1/snapshots', out:'snapshots-out'},\n"
    "  trace:     {path:'/v1/trace',     out:'trace-out'},\n"
    "  models:    {path:'/v1/routes',    out:'models-out'},\n"
    "  usage:     {path:'/v1/usage',     out:'usage-out'},\n"
    "  plugins:   {path:'/v1/plugins',   out:'plugins-out'},\n"
    "  skills:    {path:'/v1/skills',    out:'skills-out'},\n"
    "  mcp:       {path:'/v1/mcp',       out:'mcp-out'},\n"
    "  cluster:   {path:'/v1/cluster',   out:'cluster-out'},\n"
    "  metrics:   {path:'/metrics',      out:'metrics-out'},\n"
    "};\n"
    "\n"
    "async function load(panel){\n"
    "  if(panel === 'metrics'){\n"
    "    const r = await call('GET','/metrics');\n"
    "    const el = $('metrics-out'); if(el) el.textContent = r.text;\n"
    "    return;\n"
    "  }\n"
    "  const f = fetchers[panel];\n"
    "  if(!f) return;\n"
    "  const r = await call('GET', f.path);\n"
    "  const el = $(f.out); if(el) el.textContent = JSON.stringify(r.obj, null, 2);\n"
    "}\n"
    "\n"
    "async function rollback(){\n"
    "  const r = await call('POST','/v1/snapshots/rollback');\n"
    "  $('snapshots-out').textContent = JSON.stringify(r.obj, null, 2);\n"
    "  load('snapshots');\n"
    "}\n"
    "\n"
    "async function runSkill(){\n"
    "  const name = $('skillname').value.trim();\n"
    "  if(!name) return;\n"
    "  const r = await call('POST','/v1/skills/run',{name});\n"
    "  $('skills-out').textContent = JSON.stringify(r.obj, null, 2);\n"
    "}\n"
    "\n"
    "/* ---- navigation ---- */\n"
    "let current = 'tasks';\n"
    "function switchPanel(p){\n"
    "  current = p;\n"
    "  document.querySelectorAll('#nav button').forEach(b => b.classList.toggle('on', b.dataset.p === p));\n"
    "  $('content').innerHTML = panels[p];\n"
    "  if(p === 'tasks') return;\n"
    "  load(p);\n"
    "}\n"
    "\n"
    "document.querySelectorAll('#nav button').forEach(b => {\n"
    "  b.addEventListener('click', () => switchPanel(b.dataset.p));\n"
    "});\n"
    "\n"
    "/* init */\n"
    "$('content').innerHTML = panels.tasks;\n"
    "$('prompt').addEventListener('keydown', e => { if(e.key==='Enter' && (e.ctrlKey||e.metaKey)) runTask(); });\n"
    "</script>\n"
    "</body>\n"
    "</html>\n"
    "\n"
    ;
