/* web_ui.h — GENERATED from apps/web/index.html by tools/gen_web_ui.py.
 * Do not edit by hand; re-run the generator after changing the HTML. */
#pragma once
static const char ca_web_index_html[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"zh\">\n"
    "<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "<title>c-agent — Cognitive OS Console</title>\n"
    "<style>\n"
    "  :root{--bg:#0f1115;--card:#171a21;--border:#262b36;--fg:#e6e6e6;--muted:#8a93a3;--accent:#2f6feb;--ok:#4ade80;--warn:#ffd166;--sidebar:#0b0d11;--nav-hover:#14171d;--nav-on:#1a1f2b;--input:#2c3340}\n"
    "  body[data-theme=light]{--bg:#f4f6fa;--card:#fff;--border:#d9dfe8;--fg:#1c2333;--muted:#5a6478;--accent:#2563eb;--ok:#15803d;--warn:#b45309;--sidebar:#e9edf3;--nav-hover:#dfe5ee;--nav-on:#fff;--input:#cbd5e1}\n"
    "  body[data-theme=ocean]{--bg:#0a1420;--card:#0f1d2e;--border:#1e3550;--fg:#d7e7ff;--muted:#7fa3c9;--accent:#38bdf8;--ok:#34d399;--warn:#fbbf24;--sidebar:#08111b;--nav-hover:#102236;--nav-on:#123049;--input:#1e3550}\n"
    "  body[data-theme=forest]{--bg:#0d1410;--card:#13201a;--border:#22382d;--fg:#d9f2e4;--muted:#8fb8a0;--accent:#34d399;--ok:#4ade80;--warn:#fbbf24;--sidebar:#0a100c;--nav-hover:#16261e;--nav-on:#1c3a2b;--input:#22382d}\n"
    "  body[data-theme=sunset]{--bg:#171019;--card:#221a24;--border:#3a2c40;--fg:#f0e2ee;--muted:#b39bb0;--accent:#e879f9;--ok:#4ade80;--warn:#fbbf24;--sidebar:#120c14;--nav-hover:#2a1f2d;--nav-on:#3a2c40;--input:#3a2c40}\n"
    "  *{box-sizing:border-box}\n"
    "  body{font-family:system-ui,Segoe UI,Roboto,sans-serif;background:var(--bg);color:var(--fg);margin:0;display:flex;height:100vh;overflow:hidden}\n"
    "  aside{width:210px;background:var(--sidebar);border-right:1px solid var(--border);padding:16px 0;display:flex;flex-direction:column;flex-shrink:0}\n"
    "  aside h1{font-size:15px;margin:0 16px 4px}\n"
    "  aside .sub{color:var(--muted);font-size:11px;margin:0 16px 16px}\n"
    "  nav{flex:1;overflow-y:auto}\n"
    "  nav button{display:block;width:100%;text-align:left;background:none;border:0;color:var(--fg);padding:9px 16px;font-size:13px;cursor:pointer}\n"
    "  nav button:hover{background:var(--nav-hover)}\n"
    "  nav button.on{background:var(--nav-on);border-left:3px solid var(--accent);color:var(--fg)}\n"
    "  main{flex:1;display:flex;flex-direction:column;min-width:0}\n"
    "  .top{display:flex;align-items:center;justify-content:space-between;padding:14px 20px;border-bottom:1px solid var(--border)}\n"
    "  .top .title{font-size:14px;font-weight:600}\n"
    "  .top .flow{color:var(--muted);font-size:11px;letter-spacing:.5px}\n"
    "  .content{flex:1;padding:20px;overflow-y:auto}\n"
    "  .card{background:var(--card);border:1px solid var(--border);border-radius:8px;padding:14px;margin-bottom:14px}\n"
    "  .card h2{font-size:13px;margin:0 0 10px;color:var(--fg)}\n"
    "  .hint{color:var(--muted);font-size:12px;margin:4px 0 10px}\n"
    "  textarea,input[type=text],select{width:100%;background:var(--bg);color:var(--fg);border:1px solid var(--input);border-radius:6px;padding:8px;font-family:ui-monospace,Consolas,monospace;font-size:13px}\n"
    "  select{height:36px;cursor:pointer}\n"
    "  textarea{height:64px}\n"
    "  .topright{display:flex;align-items:center;gap:14px}\n"
    "  #theme{width:auto;min-width:90px}\n"
    "  button.sm{padding:4px 8px;font-size:12px}\n"
    "  button.danger{background:transparent;color:#f87171;border:1px solid #f87171}\n"
    "  button.danger:hover{background:#f871711a}\n"
    "  .row{display:flex;gap:8px;align-items:center;margin-top:8px;flex-wrap:wrap}\n"
    "  button{background:var(--accent);color:#fff;border:0;border-radius:6px;padding:8px 14px;font-size:13px;cursor:pointer}\n"
    "  button.sec{background:var(--card);border:1px solid var(--border);color:var(--fg)}\n"
    "  button:disabled{opacity:.5;cursor:not-allowed}\n"
    "  pre{background:var(--bg);border:1px solid var(--border);border-radius:6px;padding:10px;font-size:12px;overflow:auto;white-space:pre-wrap;word-break:break-word;max-height:50vh;min-height:60px;margin:0}\n"
    "  .badge-ok{color:var(--ok)} .badge-warn{color:var(--warn)}\n"
    "  table{width:100%;border-collapse:collapse;font-size:12px}\n"
    "  th,td{text-align:left;padding:6px 8px;border-bottom:1px solid var(--border)}\n"
    "  th{color:var(--muted);font-weight:600}\n"
    "  .muted{color:var(--muted)}\n"
    "  tr.active-row td{background:var(--nav-on)}\n"
    "  tr.active-row td:first-child{box-shadow:inset 3px 0 0 var(--accent)}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<aside>\n"
    "  <h1>c-agent</h1>\n"
    "  <div class=\"sub\">Cognitive OS Runtime</div>\n"
    "  <nav id=\"nav\">\n"
    "    <button data-p=\"tasks\" class=\"on\">Tasks</button>\n"
    "    <button data-p=\"tools\">Tools</button>\n"
    "    <button data-p=\"memory\">Memory</button>\n"
    "    <button data-p=\"snapshots\">Snapshots</button>\n"
    "    <button data-p=\"trace\">Trace</button>\n"
    "    <button data-p=\"models\">Models</button>\n"
    "    <button data-p=\"usage\">Usage</button>\n"
    "    <button data-p=\"plugins\">Plugins</button>\n"
    "    <button data-p=\"skills\">Skills</button>\n"
    "    <button data-p=\"mcp\">MCP</button>\n"
    "    <button data-p=\"cluster\">Cluster</button>\n"
    "    <button data-p=\"metrics\">Metrics</button>\n"
    "  </nav>\n"
    "</aside>\n"
    "\n"
    "<main>\n"
    "  <div class=\"top\">\n"
    "    <div class=\"title\">Console</div>\n"
    "    <div class=\"topright\">\n"
    "      <div class=\"flow\">RECEIVE → UNDERSTAND → REASON → PLAN → ACT → VERIFY → LEARN</div>\n"
    "      <select id=\"theme\" title=\"主题\">\n"
    "        <option value=\"dark\">Dark</option>\n"
    "        <option value=\"light\">Light</option>\n"
    "        <option value=\"ocean\">Ocean</option>\n"
    "        <option value=\"forest\">Forest</option>\n"
    "        <option value=\"sunset\">Sunset</option>\n"
    "      </select>\n"
    "    </div>\n"
    "  </div>\n"
    "  <div class=\"content\" id=\"content\"></div>\n"
    "</main>\n"
    "\n"
    "<script>\n"
    "const $ = id => document.getElementById(id);\n"
    "\n"
    "async function call(method, path, body) {\n"
    "  try {\n"
    "    const r = await fetch(path, {method, headers:{'Content-Type':'application/json'}, body: body ? JSON.stringify(body) : undefined});\n"
    "    const text = await r.text();\n"
    "    let obj; try { obj = JSON.parse(text); } catch { obj = {raw: text}; }\n"
    "    return {status: r.status, obj, text};\n"
    "  } catch (e) {\n"
    "    return {status: 0, obj: {error: String(e)}, text: ''};\n"
    "  }\n"
    "}\n"
    "\n"
    "function esc(s){ return String(s).replace(/[&<>\"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c])); }\n"
    "\n"
    "function renderPre(obj){\n"
    "  return '<div class=\"card\"><h2>Output</h2><pre>' + esc(JSON.stringify(obj, null, 2)) + '</pre></div>';\n"
    "}\n"
    "\n"
    "/* ---- panels ---- */\n"
    "const panels = {};\n"
    "\n"
    "panels.tasks = `\n"
    "  <div class=\"card\">\n"
    "    <h2>Run a task</h2>\n"
    "    <div class=\"hint\">提交一个自然语言任务，走完整 RECEIVE→…→LEARN 链路。</div>\n"
    "    <textarea id=\"prompt\" placeholder=\"例如：在 test/ 建文件 a.txt 并写入 hello\"></textarea>\n"
    "    <div class=\"row\">\n"
    "      <button onclick=\"runTask()\">Run</button>\n"
    "      <span id=\"taskstat\" class=\"muted\"></span>\n"
    "    </div>\n"
    "  </div>\n"
    "  <div class=\"card\"><h2>Result</h2><pre id=\"out\">等待输入…</pre></div>`;\n"
    "\n"
    "async function runTask(){\n"
    "  const prompt = $('prompt').value.trim();\n"
    "  if(!prompt) return;\n"
    "  $('taskstat').textContent = 'submitting…';\n"
    "  const c = await call('POST','/v1/tasks',{prompt});\n"
    "  const id = c.obj && c.obj.id;\n"
    "  if(id === undefined){ $('out').textContent = JSON.stringify(c.obj,null,2); $('taskstat').textContent=''; return; }\n"
    "  for(let i=0;i<120;i++){\n"
    "    const r = await call('GET','/v1/tasks/'+id);\n"
    "    $('out').textContent = JSON.stringify(r.obj,null,2);\n"
    "    const st = r.obj.status;\n"
    "    $('taskstat').textContent = st || '';\n"
    "    if(st==='DONE'||st==='FAILED'||st==='CANCELLED'||st==='TIMEOUT') return;\n"
    "    await new Promise(res=>setTimeout(res,300));\n"
    "  }\n"
    "}\n"
    "\n"
    "panels.tools = '<div class=\"card\"><h2>Tools</h2><pre id=\"tools-out\">加载中…</pre></div>';\n"
    "panels.memory = '<div class=\"card\"><h2>Memory</h2><pre id=\"memory-out\">加载中…</pre></div>';\n"
    "panels.snapshots = `\n"
    "  <div class=\"card\"><h2>Snapshots</h2>\n"
    "    <div class=\"row\"><button onclick=\"load('snapshots')\">Refresh</button>\n"
    "    <button class=\"sec\" onclick=\"rollback()\">Rollback latest</button></div>\n"
    "  </div>\n"
    "  <div class=\"card\"><pre id=\"snapshots-out\">加载中…</pre></div>`;\n"
    "panels.trace = '<div class=\"card\"><h2>Trace (spans)</h2><pre id=\"trace-out\">加载中…</pre></div>';\n"
    "panels.models = `\n"
    "  <div class=\"card\">\n"
    "    <h2>Model routes</h2>\n"
    "    <div class=\"hint\">管理 LLM 路由：点 <b>Set active</b> 把某条路由设为当前活跃模型（实时切换并持久化到 state/cagent.json）；<b>Delete</b> 移除一条路由。</div>\n"
    "    <div class=\"row\"><button onclick=\"loadModels()\">Refresh</button><span id=\"models-stat\" class=\"muted\"></span></div>\n"
    "    <div style=\"overflow:auto\">\n"
    "    <table>\n"
    "      <thead><tr><th>Name</th><th>Provider</th><th>Model</th><th>Base URL</th><th>W</th><th>Calls</th><th></th></tr></thead>\n"
    "      <tbody id=\"routes-body\"><tr><td colspan=\"7\" class=\"muted\">加载中…</td></tr></tbody>\n"
    "    </table>\n"
    "    </div>\n"
    "  </div>\n"
    "  <div class=\"card\">\n"
    "    <h2>Add / update route</h2>\n"
    "    <div class=\"hint\">新增或覆盖一条命名路由（相同 name 即覆盖）。保存后点 <b>Set active</b> 使其生效。</div>\n"
    "    <div class=\"row\"><input id=\"r-name\" placeholder=\"name (如 gpt4)\" style=\"flex:1;min-width:140px\"><select id=\"r-provider\"><option value=\"mock\">mock</option><option value=\"openai\">openai</option><option value=\"anthropic\">anthropic</option></select></div>\n"
    "    <div class=\"row\"><input id=\"r-model\" placeholder=\"model (如 gpt-4o)\" style=\"flex:2;min-width:180px\"><input id=\"r-base\" placeholder=\"base_url (如 https://api.openai.com/v1)\" style=\"flex:3;min-width:220px\"></div>\n"
    "    <div class=\"row\"><input id=\"r-key\" type=\"text\" placeholder=\"api_key\" style=\"flex:2;min-width:180px\"><input id=\"r-weight\" placeholder=\"weight (默认 1)\" value=\"1\" style=\"flex:1;min-width:80px\"></div>\n"
    "    <div class=\"row\"><button onclick=\"addRoute()\">Add route</button><span id=\"routes-msg\" class=\"muted\"></span></div>\n"
    "  </div>`;\n"
    "panels.usage = '<div class=\"card\"><h2>Token usage</h2><pre id=\"usage-out\">加载中…</pre></div>';\n"
    "panels.plugins = '<div class=\"card\"><h2>Plugin registry</h2><pre id=\"plugins-out\">加载中…</pre></div>';\n"
    "panels.skills = `\n"
    "  <div class=\"card\"><h2>Skills</h2>\n"
    "    <div class=\"hint\">静态 Shell/Python 技能。</div>\n"
    "    <div class=\"row\">\n"
    "      <input type=\"text\" id=\"skillname\" placeholder=\"技能名，例如 echo_hello\" style=\"flex:1;min-width:180px\">\n"
    "      <button onclick=\"runSkill()\">Run</button>\n"
    "    </div>\n"
    "  </div>\n"
    "  <div class=\"card\"><pre id=\"skills-out\">加载中…</pre></div>`;\n"
    "panels.mcp = '<div class=\"card\"><h2>MCP connections</h2><pre id=\"mcp-out\">加载中…</pre></div>';\n"
    "panels.cluster = '<div class=\"card\"><h2>Cluster nodes</h2><pre id=\"cluster-out\">加载中…</pre></div>';\n"
    "panels.metrics = '<div class=\"card\"><h2>Metrics</h2><pre id=\"metrics-out\">加载中…</pre></div>';\n"
    "\n"
    "const fetchers = {\n"
    "  tools:     {path:'/v1/tools',     out:'tools-out'},\n"
    "  memory:    {path:'/v1/memory',    out:'memory-out'},\n"
    "  snapshots: {path:'/v1/snapshots', out:'snapshots-out'},\n"
    "  trace:     {path:'/v1/trace',     out:'trace-out'},\n"
    "  models:    {path:'/v1/routes',    out:'models-out'},\n"
    "  usage:     {path:'/v1/usage',     out:'usage-out'},\n"
    "  plugins:   {path:'/v1/plugins',   out:'plugins-out'},\n"
    "  skills:    {path:'/v1/skills',    out:'skills-out'},\n"
    "  mcp:       {path:'/v1/mcp',       out:'mcp-out'},\n"
    "  cluster:   {path:'/v1/cluster',   out:'cluster-out'},\n"
    "  metrics:   {path:'/metrics',      out:'metrics-out'},\n"
    "};\n"
    "\n"
    "async function load(panel){\n"
    "  if(panel === 'models') return loadModels();\n"
    "  if(panel === 'metrics'){\n"
    "    const r = await call('GET','/metrics');\n"
    "    const el = $('metrics-out'); if(el) el.textContent = r.text;\n"
    "    return;\n"
    "  }\n"
    "  const f = fetchers[panel];\n"
    "  if(!f) return;\n"
    "  const r = await call('GET', f.path);\n"
    "  const el = $(f.out); if(el) el.textContent = JSON.stringify(r.obj, null, 2);\n"
    "}\n"
    "\n"
    "async function rollback(){\n"
    "  const r = await call('POST','/v1/snapshots/rollback');\n"
    "  $('snapshots-out').textContent = JSON.stringify(r.obj, null, 2);\n"
    "  load('snapshots');\n"
    "}\n"
    "\n"
    "async function runSkill(){\n"
    "  const name = $('skillname').value.trim();\n"
    "  if(!name) return;\n"
    "  const r = await call('POST','/v1/skills/run',{name});\n"
    "  $('skills-out').textContent = JSON.stringify(r.obj, null, 2);\n"
    "}\n"
    "\n"
    "/* ---- models config ---- */\n"
    "let ROUTES = [];\n"
    "let ACTIVE = {provider:'', model:'', api_key_set:false};\n"
    "\n"
    "async function loadModels(){\n"
    "  const r  = await call('GET','/v1/routes');\n"
    "  const cfg = await call('GET','/v1/config/llm');\n"
    "  ROUTES = Array.isArray(r.obj) ? r.obj : [];\n"
    "  ACTIVE = (cfg.obj && typeof cfg.obj === 'object') ? cfg.obj : ACTIVE;\n"
    "  const st = $('models-stat');\n"
    "  if(st) st.textContent = 'active: ' + (ACTIVE.provider || '?')\n"
    "      + (ACTIVE.model ? ' / ' + ACTIVE.model : '')\n"
    "      + (ACTIVE.api_key_set ? '' : ' (未配置 api_key)');\n"
    "  const t = $('routes-body');\n"
    "  if(!t) return;\n"
    "  if(!ROUTES.length){ t.innerHTML = '<tr><td colspan=\"7\" class=\"muted\">(empty)</td></tr>'; return; }\n"
    "  const ap = ACTIVE.provider || '';\n"
    "  t.innerHTML = ROUTES.map((x,i) => {\n"
    "    const isActive = x.name === ap;  /* set_llm keys the active route by provider */\n"
    "    return '<tr class=\"'+(isActive?'active-row':'')+'\">'\n"
    "      +'<td>'+esc(x.name||'')+(isActive?' <span class=\"badge-ok\">● active</span>':'')+'</td>'\n"
    "      +'<td>'+esc(x.provider||'')+'</td>'\n"
    "      +'<td>'+esc(x.model||'')+'</td>'\n"
    "      +'<td class=\"muted\">'+esc(x.base_url||'')+'</td>'\n"
    "      +'<td>'+(x.weight!=null?x.weight:1)+'</td>'\n"
    "      +'<td>'+(x.calls!=null?x.calls:0)+'</td>'\n"
    "      +'<td><button onclick=\"setActive('+i+')\" class=\"sec sm\"'+(isActive?' disabled':'')+'>Set active</button> '\n"
    "      +'<button onclick=\"deleteRoute('+i+')\" class=\"sec sm danger\">Delete</button></td></tr>';\n"
    "  }).join('');\n"
    "}\n"
    "\n"
    "async function setActive(i){\n"
    "  const x = ROUTES[i]; if(!x) return;\n"
    "  const st = $('models-stat'); if(st) st.textContent = 'switching…';\n"
    "  const r = await call('POST','/v1/config/llm',{\n"
    "    provider: x.provider, base_url: x.base_url||'', model: x.model||'', api_key: x.api_key||''\n"
    "  });\n"
    "  if(st) st.textContent = (r.obj && r.obj.ok)\n"
    "      ? 'switched to ' + (x.model || x.provider)\n"
    "      : (r.obj && r.obj.error) ? 'error: ' + r.obj.error : 'error ' + r.status;\n"
    "  loadModels();\n"
    "}\n"
    "\n"
    "async function deleteRoute(i){\n"
    "  const x = ROUTES[i]; if(!x) return;\n"
    "  const r = await call('DELETE','/v1/routes/'+encodeURIComponent(x.name));\n"
    "  loadModels();\n"
    "}\n"
    "\n"
    "async function addRoute(){\n"
    "  const name = $('r-name').value.trim();\n"
    "  const provider = $('r-provider').value;\n"
    "  const msg = $('routes-msg');\n"
    "  if(!name){ if(msg) msg.textContent = 'need name'; return; }\n"
    "  const body = {\n"
    "    name, provider,\n"
    "    base_url: $('r-base').value.trim(),\n"
    "    model: $('r-model').value.trim(),\n"
    "    api_key: $('r-key').value.trim()\n"
    "  };\n"
    "  const w = parseFloat($('r-weight').value);\n"
    "  if(!isNaN(w)) body.weight = w;\n"
    "  const r = await call('POST','/v1/routes',body);\n"
    "  if(msg) msg.textContent = (r.status < 300) ? 'route saved'\n"
    "      : (r.obj && r.obj.error) ? 'error: ' + r.obj.error : 'error ' + r.status;\n"
    "  if(r.status < 300){\n"
    "    $('r-name').value=''; $('r-base').value=''; $('r-key').value=''; $('r-model').value='';\n"
    "  }\n"
    "  loadModels();\n"
    "}\n"
    "\n"
    "/* ---- navigation ---- */\n"
    "let current = 'tasks';\n"
    "function switchPanel(p){\n"
    "  current = p;\n"
    "  document.querySelectorAll('#nav button').forEach(b => b.classList.toggle('on', b.dataset.p === p));\n"
    "  $('content').innerHTML = panels[p];\n"
    "  if(p === 'tasks') return;\n"
    "  load(p);\n"
    "}\n"
    "\n"
    "document.querySelectorAll('#nav button').forEach(b => {\n"
    "  b.addEventListener('click', () => switchPanel(b.dataset.p));\n"
    "});\n"
    "\n"
    "/* ---- theme ---- */\n"
    "const THEMES = ['dark','light','ocean','forest','sunset'];\n"
    "function applyTheme(t){\n"
    "  if(!THEMES.includes(t)) t = 'dark';\n"
    "  document.body.dataset.theme = t;\n"
    "  localStorage.setItem('cagent-theme', t);\n"
    "  const sel = $('theme'); if(sel) sel.value = t;\n"
    "}\n"
    "$('theme').addEventListener('change', e => applyTheme(e.target.value));\n"
    "applyTheme(localStorage.getItem('cagent-theme') || 'dark');\n"
    "\n"
    "/* init */\n"
    "$('content').innerHTML = panels.tasks;\n"
    "$('prompt').addEventListener('keydown', e => { if(e.key==='Enter' && (e.ctrlKey||e.metaKey)) runTask(); });\n"
    "</script>\n"
    "</body>\n"
    "</html>\n"
    "\n"
    ;
